force-app/main/default/objects/Error_Logger_Event__e/Error_Logger_Event__e.object-meta.xml
<CustomObject>
    <label>Error Logger Event</label>
    <pluralLabel>Error Logger Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Error_Logger_Event__e/fields/Brief_Description__c.field-meta.xml
<CustomField>
    <fullName>Brief_Description__c</fullName>
    <description>This is to store the short descripton of the error message</description>
    <label>Brief Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logger_Event__e/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <description>This is to store the name of the process that is being executed</description>
    <label>Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger_Event__e/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>This is to store the complete details of the error.</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logger_Event__e/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <description>This is to store the Input(Parameter) that is provided for the particular method.</description>
    <label>Input</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logger_Event__e/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>This is to store the Name of the Object that Process,Trigger has.</description>
    <label>Object Name</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger_Event__e/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>This is to store the Identify the severity of the record.</description>
    <label>Severity</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger_Event__e/fields/TransactionDateTime__c.field-meta.xml
<CustomField>
    <fullName>TransactionDateTime__c</fullName>
    <description>This is to store the transaction time</description>
    <label>TransactionDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Logger_Event__e/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <description>This is to store the UserName who is executing the process</description>
    <label>User ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorLoggerEventTriggerTest.cls
@isTest
public class ErrorLoggerEventTriggerTest {
    static testmethod void eventTriggerTest(){
        
        
        
          User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        system.runAs(thisUser){
       
        	 UserRole r = new UserRole(DeveloperName = 'MyCustomRole', Name = 'My Role');
        	 insert r;
        
        	 User u = new User(
     		 ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
             LastName = 'last',
             Email = 'puser000@amamama.com',
             Username = 'puser000@amamama.com' + System.currentTimeMillis(),
             CompanyName = 'TEST',
             Title = 'title',
             Alias = 'alias',
             TimeZoneSidKey = 'America/Los_Angeles',
             EmailEncodingKey = 'UTF-8',
             LanguageLocaleKey = 'en_US',
             LocaleSidKey = 'en_US',
             UserRoleId = r.Id
        );
            insert u;
              Error_Logger_Event__e errLoggerEvent =new Error_Logger_Event__e();
        errLoggerEvent.Component_Name__c ='Test';
        errLoggerEvent.Brief_Description__c ='Error Message';
        //errLoggerEvent.CreatedDate =system.today();
       // errLoggerEvent.User_ID__c ='1234ttew';
        errLoggerEvent.Object_Name__c ='Account';
        errLoggerEvent.Severity__c ='Test';
        errLoggerEvent.Error_Message__c ='test';
       errLoggerEvent.Input__c ='UnKnown';
        errLoggerEvent.TransactionDateTime__c =system.today();
        errLoggerEvent.User_ID__c=u.id;
            
         Test.startTest();
          Database.SaveResult sr = EventBus.publish(errLoggerEvent);

        EventBus.publish(errLoggerEvent);
        
        test.stopTest();
        }
      
   
    }

}