force-app/main/default/objects/Error_Logger_Event__e/Error_Logger_Event__e.object-meta.xml
<CustomObject>
    <label>Error Logger Event</label>
    <pluralLabel>Error Logger Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Error_Logger_Event__e/fields/Brief_Description__c.field-meta.xml
<CustomField>
    <fullName>Brief_Description__c</fullName>
    <description>This is to store the short descripton of the error message</description>
    <label>Brief Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logger_Event__e/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <description>This is to store the name of the process that is being executed</description>
    <label>Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger_Event__e/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>This is to store the complete details of the error.</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logger_Event__e/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <description>This is to store the Input(Parameter) that is provided for the particular method.</description>
    <label>Input</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logger_Event__e/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>This is to store the Name of the Object that Process,Trigger has.</description>
    <label>Object Name</label>
    <length>70</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger_Event__e/fields/TransactionDateTime__c.field-meta.xml
<CustomField>
    <fullName>TransactionDateTime__c</fullName>
    <description>This is to store the transaction time</description>
    <label>TransactionDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Error_Logger_Event__e/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <description>This is to store the UserName who is executing the process</description>
    <label>User ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CatchAndPublishExceptionEvent.cls
/**************************************************************************************************
*** Class Name             : CatchAndPublishExceptionEvent
*** Class Description      : Whenever exception is raised in org. we publish the error logger event
*** Author                 : Coreflex Solutions
*** Class Created Date     : 
*** Configurable Parameters:
*        End Point URL     :
*        Custom Labels Used:
*        Custom Object Used: 
*** Change Management      :
*        Change #          : 
*        Change Description:
*        Modified Date     :
*        Modified By       :
**************************************************************************************************/

public class CatchAndPublishExceptionEvent {
    
        
    /**************************************************************************************************
*** Method Name             : getExceptionDetails
*** Method Description      : This method creates a event by using  the details provided
**********************************************************************************************************/
    
    public static void getExceptionDetails(Exception e, String userID, List<SObject> listOfRecords, sObject singleRecord, String inputFromMethodParameters){
        Schema.SObjectType sobjectType;
        string objectName = '';
        string briefDescription = '';
        string userDefinedInput = '';
        if(e.getTypeName().contains('System.DmlException')){
            Integer numErrors = e.getNumDml();
            for(Integer i=0;i<numErrors;i++) {
                briefDescription = briefDescription + ' ' + e.getDmlMessage(i);
            }   
        }else{
            briefDescription = e.getMessage();
        }
        
        if(inputFromMethodParameters != null){
            userDefinedInput = inputFromMethodParameters;
        }else if(listOfRecords != null){
            userDefinedInput = String.valueOf(listOfRecords);
        }else if(singleRecord != null){
            userDefinedInput = String.valueOf(singleRecord);
        }
        
        if(singleRecord != null){
            objectName =String.valueOf(singleRecord.getSObjectType());
        }
        if(listOfRecords !=null){
            objectName = String.valueOf(listOfRecords.getSObjectType());
        }
        
        Error_Logger_Event__e errorEvent = new Error_Logger_Event__e(Component_Name__c=e.getStackTraceString(),
                                                                     User_ID__c = userID,
                                                                     Object_Name__c =objectName,
                                                                     Error_Message__c = String.valueOf(e),
                                                                     Brief_Description__c = briefDescription,
                                                                     TransactionDateTime__c = system.now(),
                                                                     Input__c = userDefinedInput
                                                                    );
        
        Database.SaveResult eventResult = EventBus.publish(errorEvent);
        if (eventResult.isSuccess()) {
            System.debug('Successfully published event.');
        } else {
            for(Database.Error err : eventResult.getErrors()) {
                System.debug('Error returned: ' + err.getStatusCode() + ' - ' + err.getMessage());
            }
        }
    }
}