force-app/main/default/objects/Error_Logger__c/Error_Logger__c.object-meta.xml
<CustomObject>
    <label>Error Logger</label>
    <nameField>
        <displayFormat>IN-{0}</displayFormat>
        <label>Incident Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Logger__c/fields/Archival_Date__c.field-meta.xml
<CustomField>
    <fullName>Archival_Date__c</fullName>
    <label>Archival Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Brief_Description__c.field-meta.xml
<CustomField>
    <fullName>Brief_Description__c</fullName>
    <description>This is to store the short descripton of the error message</description>
    <label>Brief Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <description>This is to store the name of the process that is being executed</description>
    <label>Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <description>This is to store the name type of the process that is being executed</description>
    <label>Component Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Workflow</fullName>
            </value>
            <value>
                <fullName>Apex Class</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Apex Job</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>This is to store the complete details of the error.</description>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <description>This is to store the Input(Parameter) that is provided for the particular method.</description>
    <inlineHelpText>This contains the data that is used while issue is raised.</inlineHelpText>
    <label>Input</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>This is to store the Name of the Object that Process,Trigger has.</description>
    <label>Object Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>This is to store the Identify the severity of the record.</description>
    <label>Severity</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Supervisor__c.field-meta.xml
<CustomField>
    <fullName>Supervisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Supervisor</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Error Loggers (Supervisor)</relationshipLabel>
    <relationshipName>Error_Loggers2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/TransactionDateTime__c.field-meta.xml
<CustomField>
    <fullName>TransactionDateTime__c</fullName>
    <description>This is to store the transaction time</description>
    <label>TransactionDateTime</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <label>User ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Loggers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ErrorloggerScheduler.cls
/**************************************************************************************************
*** Trigger Name           : ErrorloggerScheduler
*** Class Description      : This class is invoked by the ErrorloggerScheduler by passing the list 
                             of Records which will be archived under ArchivalErrorLogger and deleted
                             from ErrorLogger.
*** Author                 : Coreflex Solutions
*** Class Created Date     : 
*** Configurable Parameters:
*        End Point URL     :
*        Custom Labels Used:
*        Custom Object Used: 
*** Change Management      :
*        Change #          : 
*        Change Description:
*        Modified Date     :
*        Modified By       :
**************************************************************************************************/
global class ErrorloggerScheduler implements Schedulable {
   global void execute(SchedulableContext SC) {
 List<Error_Logger__c> errorLoggerRecordsList = [SELECT Id, Name, Component_Type__c, Component_Name__c, 
                                                        Closed_Date__c, Brief_Description__c, Object_Name__c, Input__c, 
                                                        Severity__c, Status__c,  Error_Message__c, User_Name__c,
                                                        User_ID__c, TransactionDateTime__c, Supervisor__c 
                                                        FROM Error_Logger__c where Archival_Date__c =:system.today()];
            
       if(errorLoggerRecordsList.size()>0){
           ErrorloggerSchedulerHelper.moveRecordsToArchieve(errorLoggerRecordsList);
       }   
}
}