force-app/main/default/objects/Error_Logger__c/Error_Logger__c.object-meta.xml
<CustomObject>
    <label>Error Logger</label>
    <nameField>
        <displayFormat>IN-{0}</displayFormat>
        <label>Incident Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Logger__c/fields/Archival_Date__c.field-meta.xml
<CustomField>
    <fullName>Archival_Date__c</fullName>
    <label>Archival Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <description>This is to store the name of the process that is being executed</description>
    <label>Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <description>This is to store the name type of the process that is being executed</description>
    <label>Component Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Workflow</fullName>
            </value>
            <value>
                <fullName>Apex Class</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Apex Job</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>This is to store the Name of the Object that Process,Trigger has.</description>
    <label>Object Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <label>Resolution</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ErrorloggerSchedulerTest.cls
@isTest
public class ErrorloggerSchedulerTest {
   
   @isTest static void errorLoggerRecrdDeleteTest(){
        
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        system.runAs(thisUser){
       
        	 UserRole r = new UserRole(DeveloperName = 'MyCustomRole', Name = 'My Role');
        	 insert r;
        
        	 User u = new User(
     		 ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
             LastName = 'last',
             Email = 'puser000@amamama.com',
             Username = 'puser000@amamama.com' + System.currentTimeMillis(),
             CompanyName = 'TEST',
             Title = 'title',
             Alias = 'alias',
             TimeZoneSidKey = 'America/Los_Angeles',
             EmailEncodingKey = 'UTF-8',
             LanguageLocaleKey = 'en_US',
             LocaleSidKey = 'en_US',
             UserRoleId = r.Id
        );
            insert u;
            
        Error_Logger__c errorLoggr =new Error_Logger__c();
        errorLoggr.Component_Type__c ='Unknown';
        errorLoggr.Component_Name__c ='Testing_for_Error_Logger';
        errorloggr.Archival_Date__c =system.today();
        errorloggr.Object_Name__c ='Unknown';
        errorloggr.Status__c ='open';
        errorloggr.Resolution__c ='';
        insert errorloggr;
        }

        
        Test.startTest();
        ErrorloggerScheduler  errorLoggerShcdlr =new ErrorloggerScheduler();
        String sch = '0 0 1 1 * ?';
        system.schedule('Test Territory Check', sch, errorLoggerShcdlr);
 
        Test.stopTest();
        
    }
}