force-app/main/default/objects/Asset/fields/Integration_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Integration_Requested_Date__c</fullName>
    <label>Integration Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Line of Business</label>
    <referenceTo>Line_of_Business__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Manuafacturer_Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Manuafacturer_Item_Number__c</fullName>
    <description>Covetrus part number.CCRM-83</description>
    <label>Manuafacturer Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Manufacturer__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer__c</fullName>
    <description>The product make.CCRM-83</description>
    <label>Manufacturer</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Product name.CCRM-83</description>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Hardware.recordType-meta.xml
<RecordType>
    <fullName>Hardware</fullName>
    <active>true</active>
    <description>This asset category describes the hardware assets sold to an Animal Care Business (Clinic) that support or are used in conjunction with a sold software asset.</description>
    <label>Hardware</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Services.recordType-meta.xml
<RecordType>
    <fullName>Services</fullName>
    <active>true</active>
    <description>This asset category describes those services provided by or brokered by Covetrus. Practice consulting services, lab services, training, etc</description>
    <label>Services</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Software.recordType-meta.xml
<RecordType>
    <fullName>Software</fullName>
    <active>true</active>
    <description>This asset category describes the Practice management software to include the configuration of that software (modules and versions) that has been sold to a particular Animal Care Business (Clinic)</description>
    <label>Software</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Support.recordType-meta.xml
<RecordType>
    <fullName>Support</fullName>
    <active>true</active>
    <description>This asset category describes maintenance support agreements for Practice Management or Practice Performance assets that are provided.</description>
    <label>Support</label>
</RecordType>

force-app/main/default/objects/Line_of_Business__c/Line_of_Business__c.object-meta.xml
<CustomObject>
    <label>Line of Business</label>
    <nameField>
        <label>Line of Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line of Businesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_of_Business__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GSS</fullName>
            </value>
            <value>
                <fullName>GPM</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>Specialty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Bundle_Key__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Key__c</fullName>
    <label>Bundle Key</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GSS</fullName>
            </value>
            <value>
                <fullName>GPM</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Manufacturer_Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer_Item_Number__c</fullName>
    <label>Manufacturer Item Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Hardware.recordType-meta.xml
<RecordType>
    <fullName>Hardware</fullName>
    <active>true</active>
    <label>Hardware</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Products.recordType-meta.xml
<RecordType>
    <fullName>Products</fullName>
    <active>true</active>
    <label>Products</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Services.recordType-meta.xml
<RecordType>
    <fullName>Services</fullName>
    <active>true</active>
    <label>Services</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Software.recordType-meta.xml
<RecordType>
    <fullName>Software</fullName>
    <active>true</active>
    <label>Software</label>
</RecordType>

force-app/main/default/classes/AssetTriggerHelper.cls
/**************************************************************************************************
*** Class Name             : AssetTriggerHelper
*** Class Description      : This Helper class is invoked from the trigger when trigger events are
fired.
*** Author                 : Sreenath Dhanireddy
*** Class Created Date     : 11/7/2019
*            Modified Date : 11/13/2019
*            Modified By   : Nagarjuna G
**************************************************************************************************/
public class AssetTriggerHelper {
    Public Static final String Asset_Software_Recordtype ='Software';
    Public Static final String Asset_PracticePerformance_Recordtype ='Practice Performance';
    Public Static final String Asset_Support_Recordtype ='Support';
    
    /************************************************************************************************
*** Method Name             : assetCreation
*** Method Description      : This method will create subassets for those products that are associated
via a bundle id to the main product(Parent Asset).
*****************************************************************************************************/
    public static void assetCreation(List<Asset> assetList){
        set<String> prodCodes = new Set<String>();
        map<string,id> assetProdMap = new map<string,id>();
        list<asset> asstList = new list<asset>();
        map<string,list<product2>> prodBundleKeyMap = new map<string,list<product2>>();
        try{
            for(Asset asset : assetList){
                if (!String.isEmpty(asset.ProductCode)) {
	                prodCodes.add(asset.ProductCode);
    	            assetProdMap.put(asset.Product2Id,asset.Id);
                }
            }
            if (!prodCodes.isEmpty()) {
                List<Product2> prodList = [SELECT ID, Name, Bundle_Key__c, Family, Manufacturer__c, Manufacturer_Item_Number__c 
                                           FROM Product2 WHERE Bundle_Key__c IN: prodCodes];  
                for(product2 prod: prodList){
                    if(prodBundleKeyMap.containskey(prod.Bundle_Key__c)){
                        List<product2> bundleKeyProdList = prodBundleKeyMap.get(prod.Bundle_Key__c);
                        bundleKeyProdList.add(prod);
                        prodBundleKeyMap.put(prod.Bundle_Key__c, bundleKeyProdList);
                    } else {
                        prodBundleKeyMap.put(prod.Bundle_Key__c, new List<product2> { prod });
                    }
                }
            }
            for(asset ass: assetList){
                if (prodBundleKeyMap.containsKey(ass.ProductCode)) {
                    for(product2 prod: prodBundleKeyMap.get(ass.ProductCode)){
                        if(!assetProdMap.keyset().contains(prod.Id) && ass.ParentId==null){
                            Asset asst =  new Asset();
                            asst.Product2Id = prod.Id;
                            asst.ParentId = ass.Id;
                            asst.Status = ass.Status;
                            asst.AccountId = ass.AccountId;
                            asst.Name = prod.Name;
                            asst.Line_of_Business__c= ass.Line_of_Business__c;
                            asst.PurchaseDate = ass.PurchaseDate;
                            if(prod.Family == 'Covetrus Software' || prod.Family == '3rd Party Software'){
                                asst.RecordTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Software').getRecordTypeId();
                            }
                            else if(prod.Family == 'Hardware' || prod.Family == 'Warranty' || prod.Family == 'Product'){
                                asst.RecordTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Hardware').getRecordTypeId();
                                asst.Manufacturer__c = prod.Manufacturer__c;
                                asst.Product_Name__c = prod.Name;
                                asst.Manuafacturer_Item_Number__c = prod.Manufacturer_Item_Number__c;
                            }
                            else if(prod.Family == 'Support')
                                asst.RecordTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Support').getRecordTypeId();
                            else if(prod.Family == 'Configuration and Setup' || prod.Family == 'Professional Services')
                                asst.RecordTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Services').getRecordTypeId();
                            else if(prod.Family == 'Practice Performance')
                                asst.RecordTypeId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Practice Performance').getRecordTypeId();
                            
                            asstList.add(asst);
                        }
                    }
                }
            }
            if(asstList.size()>0){
                insert asstList;
            }
        }
        catch(Exception e){
            String inputFromMethodParameters = CaptureInputFromApexMethod.captureAndReturnInput(string.valueOf('List<Asset>'), string.valueOf(assetList), null, null, null, null, null, null, null, null);
            CatchAndPublishExceptionEvent.getExceptionDetails(e, UserInfo.getUserId(), null, null, inputFromMethodParameters);
        }
    }
    /************************************************************************************************
*** Method Name             : updateAssetIntegrationRequestedDate
*** Method Description      : This method will update the 'Integration Requested date'.When the asset record 
creates from 'Software' ,'Support' and 'Practice performace' record types.
*****************************************************************************************************/
    
    Public static void updateAssetIntegrationRequestedDate(List<Asset> asetList){
        List<Asset> assetListRecrds = new List<Asset>();
        try{
            for(Asset astRecs :asetList){
                system.debug('Enter');
                system.debug(astRecs.RecordType.name);
                astRecs.Integration_Requested_Date__c =System.now();
                assetListRecrds.add(astRecs);
            }
        }catch(Exception e){
            String inputFromMethodParameters = CaptureInputFromApexMethod.captureAndReturnInput(string.valueOf('List<Asset>'), string.valueOf(asetList), null, null, null, null, null, null, null, null);
            CatchAndPublishExceptionEvent.getExceptionDetails(e, UserInfo.getUserId(), null, null, inputFromMethodParameters);
        }
        
    }
    
    /************************************************************************************************
*** Method Name             : updateAssetIntegReqDateWhenFieldSetChange
*** Method Description      : This method will update the 'Integration Requested date'. when the asset record
updates from 'Software' ,'Support' and 'Practice performace' record types.
*****************************************************************************************************/
    public static void updateAssetIntegReqDateWhenFieldSetChange(List<Asset> asstRecsList){
        List<Asset> updateAstRecList = new List<Asset>();
        set<String> fieldSet = new Set<String>();
        try{
            for(Schema.Fieldsetmember fields :Schema.SObjecttype.Asset.Fieldsets.getmap().get('Integration_Fields').getfields()){
                fieldSet.add(fields.getFieldPath());
            }
            for(Asset ast : asstRecsList){
                system.debug(ast.RecordType.name);
                for(String fieldSetList : fieldSet){
                    if(ast.get(fieldSetList) != trigger.oldmap.get(ast.id).get(fieldSetList)){
                        ast.Integration_Requested_Date__c = System.now();
                        updateAstRecList.add(ast);
                        system.debug('updateAstRecList'+updateAstRecList);
                    }
                    
                }
                
            }
            
        }catch(Exception e){
            String inputFromMethodParameters = CaptureInputFromApexMethod.captureAndReturnInput(string.valueOf('List<Asset>'), string.valueOf(asstRecsList), null, null, null, null, null, null, null, null);
            CatchAndPublishExceptionEvent.getExceptionDetails(e, UserInfo.getUserId(), null, null, inputFromMethodParameters);
        }
        
    }
}