force-app/main/default/objects/Implementation_Plan__c/Implementation_Plan__c.object-meta.xml
<CustomObject>
    <label>Implementation Plan</label>
    <nameField>
        <label>Implementation Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Plan__c/fields/Actual_Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Go_Live_Date__c</fullName>
    <description>The date for the estimation of GO Live plans</description>
    <label>Actual Go-Live Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Implementation_Plan__c/fields/Completed_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Completed_Tasks__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Completed Tasks</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Implementation_Plan__c/fields/Implementation_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Plan_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Plan Template</label>
    <referenceTo>Implementation_Plan_Template__c</referenceTo>
    <relationshipLabel>Implementation Plans</relationshipLabel>
    <relationshipName>Implementation_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Complete - Client Cancelled</fullName>
            </value>
            <value>
                <fullName>Ready to Start</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Implementation_Plan__c/fields/Total_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Total_Tasks__c</fullName>
    <label>Total Tasks</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Implementation_Plan_Template__c/Implementation_Plan_Template__c.object-meta.xml
<CustomObject>
    <label>Implementation Plan Template</label>
    <nameField>
        <label>Implementation Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Plan Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Task__c/Implementation_Task__c.object-meta.xml
<CustomObject>
    <label>Implementation Task</label>
    <nameField>
        <label>Implementation Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Task__c/fields/Implementation_Plan__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Plan</label>
    <referenceTo>Implementation_Plan__c</referenceTo>
    <relationshipLabel>Implementation Task</relationshipLabel>
    <relationshipName>Implementation_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Task__c/fields/Implementation_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Task Template</label>
    <referenceTo>Implementation_Task_Template__c</referenceTo>
    <relationshipLabel>Implementation Task</relationshipLabel>
    <relationshipName>Implementation_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Ready to Start</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Implementation_Task_Template__c/Implementation_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Implementation Task Template</label>
    <nameField>
        <label>Implementation Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Task_Template__c/fields/Implementation_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Plan_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Plan Template</label>
    <referenceTo>Implementation_Plan_Template__c</referenceTo>
    <relationshipLabel>Implementation Task Template</relationshipLabel>
    <relationshipName>Implementation_Task_Template</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Task_Template__c/fields/Revenue_Recognition__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Recognition__c</fullName>
    <label>Revenue Recognition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Software Go-Live Date</fullName>
            </value>
            <value>
                <fullName>Add-On/Module Go-Live Date</fullName>
            </value>
            <value>
                <fullName>Hardware Shipped Date</fullName>
            </value>
            <value>
                <fullName>Training Execution Date</fullName>
            </value>
            <value>
                <fullName>Data Conversion Complete Date</fullName>
            </value>
            <value>
                <fullName>Consulting Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ImplementationPlanTriggerTest.cls
/**************************************************************************************************
*** Test Class Name             : ImplementationPlanTriggerTest
*** Author                 	    : Rahim Shariff
*** Class Created Date          : 29/10/2019
*		
**************************************************************************************************/
@istest
private class ImplementationPlanTriggerTest {
    private static testmethod void test() {
        Implementation_Plan_Template__c tpl = new Implementation_Plan_Template__c(Name = 'test1');
        insert tpl;

		ContentVersion cv = new ContentVersion(Title = 'test', PathOnClient = 'test.txt', VersionData = Blob.valueOf('Test Content'), IsMajorVersion = true);
    	insert cv;

        insert new ContentDocumentLink(LinkedEntityId = tpl.Id, ShareType = 'V', ContentDocumentId = [select id from contentdocument limit 1].id);

        Implementation_Task_Template__c ttl = new Implementation_Task_Template__c(Sequence__c = 1, Implementation_Plan_Template__c = tpl.Id);
        insert ttl;

        insert new ContentDocumentLink(LinkedEntityId = ttl.Id, ShareType = 'V', ContentDocumentId = [select id from contentdocument limit 1].id);

        Implementation_Plan__c ip = new Implementation_Plan__c(Implementation_Plan_Template__c = tpl.Id);
        insert ip;

        ip = [select Name, Total_Tasks__c, Completed_Tasks__c, Actual_Go_Live_Date__c from Implementation_Plan__c where Id = :ip.Id];
        System.assert(ip.Completed_Tasks__c == 0);
        System.assert(ip.Actual_Go_Live_Date__c == null);

        Implementation_Task__c it = [select Id from Implementation_Task__c limit 1];
        it.Status__c = 'Complete';
        it.Revenue_Recognition__c = 'Software Go-Live Date';
        update it;

        ip = [select Name, Total_Tasks__c, Completed_Tasks__c, Actual_Go_Live_Date__c from Implementation_Plan__c where Id = :ip.Id];
        System.assert(ip.Name == tpl.Name);
        System.assert(ip.Total_Tasks__c > 0);
        System.assert(ip.Completed_Tasks__c == 1);
        System.assert(ip.Actual_Go_Live_Date__c != null);
    }
}