force-app/main/default/objects/Implementation_Plan__c/Implementation_Plan__c.object-meta.xml
<CustomObject>
    <label>Implementation Plan</label>
    <nameField>
        <label>Implementation Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Plan__c/fields/Implementation_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Plan_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Plan Template</label>
    <referenceTo>Implementation_Plan_Template__c</referenceTo>
    <relationshipLabel>Implementation Plans</relationshipLabel>
    <relationshipName>Implementation_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Plan_Template__c/Implementation_Plan_Template__c.object-meta.xml
<CustomObject>
    <label>Implementation Plan Template</label>
    <nameField>
        <label>Implementation Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Plan Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Task__c/Implementation_Task__c.object-meta.xml
<CustomObject>
    <label>Implementation Task</label>
    <nameField>
        <label>Implementation Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Task__c/fields/Implementation_Plan__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Plan</label>
    <referenceTo>Implementation_Plan__c</referenceTo>
    <relationshipLabel>Implementation Task</relationshipLabel>
    <relationshipName>Implementation_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Task__c/fields/Implementation_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Task Template</label>
    <referenceTo>Implementation_Task_Template__c</referenceTo>
    <relationshipLabel>Implementation Task</relationshipLabel>
    <relationshipName>Implementation_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Task__c/fields/Task_Dependency__c.field-meta.xml
<CustomField>
    <fullName>Task_Dependency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Self Lookup to Implementation Task</description>
    <label>Task Dependency</label>
    <referenceTo>Implementation_Task__c</referenceTo>
    <relationshipLabel>Implementation Task</relationshipLabel>
    <relationshipName>Implementation_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Task__c/fields/Task_Duration__c.field-meta.xml
<CustomField>
    <fullName>Task_Duration__c</fullName>
    <label>Task Duration</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Implementation_Task_Template__c/Implementation_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Implementation Task Template</label>
    <nameField>
        <label>Implementation Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Task_Template__c/fields/Dependency__c.field-meta.xml
<CustomField>
    <fullName>Dependency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Dependency</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You cannot choose a Task Template which is related to a different Implementation Plan</errorMessage>
        <filterItems>
            <field>Implementation_Task_Template__c.Implementation_Plan_Template__c</field>
            <operation>equals</operation>
            <valueField>$Source.Implementation_Plan_Template__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Implementation_Task_Template__c</referenceTo>
    <relationshipLabel>Implementation Task Template</relationshipLabel>
    <relationshipName>Implementation_Task_Template</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Task_Template__c/fields/Implementation_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Plan_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Plan Template</label>
    <referenceTo>Implementation_Plan_Template__c</referenceTo>
    <relationshipLabel>Implementation Task Template</relationshipLabel>
    <relationshipName>Implementation_Task_Template</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Task_Template__c/fields/Revenue_Recognition__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Recognition__c</fullName>
    <label>Revenue Recognition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Software Go-Live Date</fullName>
            </value>
            <value>
                <fullName>Add-On/Module Go-Live Date</fullName>
            </value>
            <value>
                <fullName>Hardware Shipped Date</fullName>
            </value>
            <value>
                <fullName>Training Execution Date</fullName>
            </value>
            <value>
                <fullName>Data Conversion Complete Date</fullName>
            </value>
            <value>
                <fullName>Consulting Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Implementation_Task_Template__c/fields/Task_Description__c.field-meta.xml
<CustomField>
    <fullName>Task_Description__c</fullName>
    <label>Task Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Implementation_Task_Template__c/fields/Task_Duration__c.field-meta.xml
<CustomField>
    <fullName>Task_Duration__c</fullName>
    <label>Task Duration</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ImplementationPlanTriggerHandler.cls
/**************************************************************************************************
*** Class Name                  : ImplementationPlanTriggerHandler
*** Author                 	    : RahimShariff
*** Class Created Date          : 29/10/2019
*		
**************************************************************************************************/

public class ImplementationPlanTriggerHandler {
    public static void setDefaults(List<Implementation_Plan__c> plans) {
        Map<Id, Implementation_Plan_Template__c> templates = new Map<Id, Implementation_Plan_Template__c>();
        for (Implementation_Plan__c ip : plans) {
            templates.put(ip.Implementation_Plan_Template__c, null);
        }
        templates = new Map<Id, Implementation_Plan_Template__c>([select Id, Name from Implementation_Plan_Template__c where Id in :templates.keySet()]);
        for (Implementation_Plan__c ip : plans) {
            if (templates.containsKey(ip.Implementation_Plan_Template__c)) {
                ip.Name = templates.get(ip.Implementation_Plan_Template__c).Name;
            }
        }
    }
    public static void spawnTasks(List<Implementation_Plan__c> plans) {
        Map<Id, Implementation_Plan_Template__c> templates = new Map<Id, Implementation_Plan_Template__c>();
        for (Implementation_Plan__c ip : plans) {
            templates.put(ip.Implementation_Plan_Template__c, null);
        }
        if (templates.isEmpty()) return;

        templates = new Map<Id, Implementation_Plan_Template__c>([select Id, (select Id, Name, OwnerId, Revenue_Recognition__c, Sequence__c, Dependency__c, Task_Description__c, Task_Duration__c from Implementation_Task_Template__r) from Implementation_Plan_Template__c where Id in :templates.keySet()]);

        Map<Id, Map<Id, Implementation_Task__c>> tasksByPlan = new Map<Id, Map<Id, Implementation_Task__c>>();
        List<Implementation_Task__c> newTasksToInsert = new List<Implementation_Task__c>();
        Map<Id, Implementation_Task_Template__c> allTaskTemplates = new Map<Id, Implementation_Task_Template__c>();
        for (Implementation_Plan__c ip : plans) {
            Implementation_Plan_Template__c ipt = templates.get(ip.Implementation_Plan_Template__c);
            if (ipt == null) continue;

            tasksByPlan.put(ip.Id, new Map<Id, Implementation_Task__c>());
            for (Implementation_Task_Template__c itt : ipt.Implementation_Task_Template__r) {
                allTaskTemplates.put(itt.Id, itt);
                Implementation_Task__c it = new Implementation_Task__c(
                    Name = itt.Name,
                    OwnerId = itt.OwnerId,
                    Sequence__c = itt.Sequence__c,
                    Task_Duration__c = itt.Task_Duration__c,
                    Implementation_Plan__c = ip.Id,
                    Implementation_Task_Template__c = itt.Id,
                    Revenue_Recognition__c = itt.Revenue_Recognition__c,
                    Task_Description__c = itt.Task_Description__c
                );
                newTasksToInsert.add(it);
                tasksByPlan.get(ip.Id).put(itt.Id, it);
            }
        }
        if (newTasksToInsert.isEmpty()) return;

        insert newTasksToInsert;

        // now go through the tasks by plan and update dependencies
        List<Implementation_Task__c> tasksToUpdate = new list<Implementation_Task__c>();
        for (Map<Id, Implementation_Task__c> tasks : tasksByPlan.values()) {
            // if the task has a dependency, find the task that was created by that dependency and update it on the task as well
            for (Implementation_Task__c t : tasks.values()) {
                Id dependentTaskTemplate = allTaskTemplates.get(t.Implementation_Task_Template__c).Dependency__c;

                // see which task was created by that template
                Implementation_Task__c dependentTask = tasks.get(dependentTaskTemplate);
                if (dependentTask != null) {
                    tasksToUpdate.add(new Implementation_Task__c(
                        Id = t.Id,
                        Task_Dependency__c = dependentTask.Id
                    ));
                }
            }
        }
        if (!tasksToUpdate.isEmpty()) update tasksToUpdate;
    }
    public static void copyFilesFromTemplate(List<Implementation_Plan__c> plans) {
        set<Id> templateIds = new set<Id>();
        for (Implementation_Plan__c ip : plans) {
            if (ip.Implementation_Plan_Template__c != null) {
                templateIds.add(ip.Implementation_Plan_Template__c);
            }
        }
        if (!templateIds.isEmpty()) {
            list<ContentDocumentLink> newCdls = new list<ContentDocumentLink>();
            for (ContentDocumentLink cdl : [select Id, ContentDocumentId, LinkedEntityId from ContentDocumentLink where LinkedEntityId in :templateIds]){
                for (Implementation_Plan__c ip : plans) {
                    if (ip.Implementation_Plan_Template__c == cdl.LinkedEntityId) {
                        newCdls.add(new ContentDocumentLink(
                            LinkedEntityId = ip.Id,
                            ShareType = 'V',
                            ContentDocumentId = cdl.ContentDocumentId
                        ));
                    }
                }
            }
            if (!newCdls.isEmpty()) insert newCdls;
        }
    }
}