force-app/main/default/objects/Implementation_Plan__c/Implementation_Plan__c.object-meta.xml
<CustomObject>
    <label>Implementation Plan</label>
    <nameField>
        <label>Implementation Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Plan__c/fields/Completed_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Completed_Tasks__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Completed Tasks</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Implementation_Plan__c/fields/Implementation_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Plan_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Plan Template</label>
    <referenceTo>Implementation_Plan_Template__c</referenceTo>
    <relationshipLabel>Implementation Plans</relationshipLabel>
    <relationshipName>Implementation_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Complete - Client Cancelled</fullName>
            </value>
            <value>
                <fullName>Ready to Start</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Implementation_Plan__c/fields/Total_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Total_Tasks__c</fullName>
    <label>Total Tasks</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Implementation_Plan_Template__c/Implementation_Plan_Template__c.object-meta.xml
<CustomObject>
    <label>Implementation Plan Template</label>
    <nameField>
        <label>Implementation Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Plan Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Task__c/Implementation_Task__c.object-meta.xml
<CustomObject>
    <label>Implementation Task</label>
    <nameField>
        <label>Implementation Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Task__c/fields/Implementation_Plan__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Plan</label>
    <referenceTo>Implementation_Plan__c</referenceTo>
    <relationshipLabel>Implementation Task</relationshipLabel>
    <relationshipName>Implementation_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Task__c/fields/Implementation_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Task Template</label>
    <referenceTo>Implementation_Task_Template__c</referenceTo>
    <relationshipLabel>Implementation Task</relationshipLabel>
    <relationshipName>Implementation_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Ready to Start</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Implementation_Task__c/fields/Task_Dependency__c.field-meta.xml
<CustomField>
    <fullName>Task_Dependency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Self Lookup to Implementation Task</description>
    <label>Task Dependency</label>
    <referenceTo>Implementation_Task__c</referenceTo>
    <relationshipLabel>Implementation Task</relationshipLabel>
    <relationshipName>Implementation_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Task_Template__c/Implementation_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Implementation Task Template</label>
    <nameField>
        <label>Implementation Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Task_Template__c/fields/Dependency__c.field-meta.xml
<CustomField>
    <fullName>Dependency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Dependency</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>You cannot choose a Task Template which is related to a different Implementation Plan</errorMessage>
        <filterItems>
            <field>Implementation_Task_Template__c.Implementation_Plan_Template__c</field>
            <operation>equals</operation>
            <valueField>$Source.Implementation_Plan_Template__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Implementation_Task_Template__c</referenceTo>
    <relationshipLabel>Implementation Task Template</relationshipLabel>
    <relationshipName>Implementation_Task_Template</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Task_Template__c/fields/Implementation_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Plan_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Plan Template</label>
    <referenceTo>Implementation_Plan_Template__c</referenceTo>
    <relationshipLabel>Implementation Task Template</relationshipLabel>
    <relationshipName>Implementation_Task_Template</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ImplementationTaskTriggerTest.cls
/**************************************************************************************************
*** Test Class Name             : ImplementationTaskTriggerTest
*** Author                 	    : Sreenath Dhanireddy
*** Class Created Date        : 29/07/2019
*		
**************************************************************************************************/
@istest
private class ImplementationTaskTriggerTest {
    private static testmethod void test() {
        Implementation_Plan_Template__c tpl = new Implementation_Plan_Template__c();
        insert tpl;

		ContentVersion cv = new ContentVersion(Title = 'test', PathOnClient = 'test.txt', VersionData = Blob.valueOf('Test Content'), IsMajorVersion = true);
    	insert cv;

        insert new ContentDocumentLink(LinkedEntityId = tpl.Id, ShareType = 'V', ContentDocumentId = [select id from contentdocument limit 1].id);

        Implementation_Task_Template__c ttl = new Implementation_Task_Template__c(Sequence__c = 1, Implementation_Plan_Template__c = tpl.Id);
        insert ttl;

        Implementation_Task_Template__c ttl2 = new Implementation_Task_Template__c(Sequence__c = 2, Implementation_Plan_Template__c = tpl.Id, Dependency__c = ttl.Id);
        insert ttl2;

        try {
        	insert new Implementation_Task_Template__c(Sequence__c = 2, Implementation_Plan_Template__c = tpl.Id, Dependency__c = ttl.Id);
            System.assert(false, 'This should have failed since it was a dupe sequence');
        } catch(Exception ex) {
            // good
        }

        insert new ContentDocumentLink(LinkedEntityId = ttl.Id, ShareType = 'V', ContentDocumentId = [select id from contentdocument limit 1].id);

        Implementation_Plan__c ip = new Implementation_Plan__c(Implementation_Plan_Template__c = tpl.Id, Total_Tasks__c = 1, Completed_Tasks__c = 0);
        insert ip;

        list<Implementation_Task__c> tasks = [select id, Sequence__c, Implementation_Plan__c from implementation_task__c];
        tasks[0].Status__c = 'Complete';

        try {
        	insert new Implementation_Task__c(Sequence__c = tasks[0].Sequence__c, Implementation_Plan__c = tasks[0].Implementation_Plan__c);
            System.assert(false, 'This should have failed since it was a dupe sequence');
        } catch(Exception ex) {
            // good
        }

        update tasks;

        System.assert([select Id from implementation_task__c where Task_Dependency__c != null].size() == 1);

        delete tasks;
        undelete tasks;
    }
}