force-app/main/default/objects/Implementation_Plan__c/Implementation_Plan__c.object-meta.xml
<CustomObject>
    <label>Implementation Plan</label>
    <nameField>
        <label>Implementation Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Plan__c/fields/Actual_Go_Live_Date__c.field-meta.xml
<CustomField>
    <fullName>Actual_Go_Live_Date__c</fullName>
    <description>The date for the estimation of GO Live plans</description>
    <label>Actual Go-Live Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Implementation_Plan__c/fields/Completed_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Completed_Tasks__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Completed Tasks</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Implementation_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Complete - Client Cancelled</fullName>
            </value>
            <value>
                <fullName>Ready to Start</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Implementation_Plan__c/fields/Total_Tasks__c.field-meta.xml
<CustomField>
    <fullName>Total_Tasks__c</fullName>
    <label>Total Tasks</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Implementation_Task__c/Implementation_Task__c.object-meta.xml
<CustomObject>
    <label>Implementation Task</label>
    <nameField>
        <label>Implementation Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Task__c/fields/Implementation_Plan__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Plan</label>
    <referenceTo>Implementation_Plan__c</referenceTo>
    <relationshipLabel>Implementation Task</relationshipLabel>
    <relationshipName>Implementation_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Task__c/fields/Implementation_Task_Template__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Task_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Task Template</label>
    <referenceTo>Implementation_Task_Template__c</referenceTo>
    <relationshipLabel>Implementation Task</relationshipLabel>
    <relationshipName>Implementation_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Task__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Ready to Start</fullName>
            </value>
            <value>
                <fullName>Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Implementation_Task__c/fields/Task_Dependency__c.field-meta.xml
<CustomField>
    <fullName>Task_Dependency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Self Lookup to Implementation Task</description>
    <label>Task Dependency</label>
    <referenceTo>Implementation_Task__c</referenceTo>
    <relationshipLabel>Implementation Task</relationshipLabel>
    <relationshipName>Implementation_Task</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Implementation_Task__c/fields/Unique_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Unique_Sequence__c</fullName>
    <label>Unique Sequence</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Implementation_Task_Template__c/Implementation_Task_Template__c.object-meta.xml
<CustomObject>
    <label>Implementation Task Template</label>
    <nameField>
        <label>Implementation Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Task Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Task_Template__c/fields/Revenue_Recognition__c.field-meta.xml
<CustomField>
    <fullName>Revenue_Recognition__c</fullName>
    <label>Revenue Recognition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Software Go-Live Date</fullName>
            </value>
            <value>
                <fullName>Add-On/Module Go-Live Date</fullName>
            </value>
            <value>
                <fullName>Hardware Shipped Date</fullName>
            </value>
            <value>
                <fullName>Training Execution Date</fullName>
            </value>
            <value>
                <fullName>Data Conversion Complete Date</fullName>
            </value>
            <value>
                <fullName>Consulting Event</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Implementation_Task_Template__c/fields/Unique_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Unique_Sequence__c</fullName>
    <description>Used to set a unique Id which is a combination of the Parent Implementation Plan Template by a Process Builder. This is to ensure that there is not an Implementation Task Template with the same sequence as another Implementation Task Template which shares the same Implementation Plan Template</description>
    <label>Unique Sequence</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ImplementationTaskTriggerHandler.cls
/**************************************************************************************************
*** Class Name             : ImplementationTaskTriggerHandler
*** Author                 	    : Sreenath Dhanireddy
*** Class Created Date        : 29/07/2019
*		
**************************************************************************************************/
public class ImplementationTaskTriggerHandler {
    public static void markCompletedDate(List<Implementation_Task__c> tasks, Map<Id, Implementation_Task__c> oldTasks) {
        for (Implementation_Task__c t : tasks) {
            if (t.Status__c == 'Complete' && t.Status__c != oldTasks.get(t.Id).Status__c) {
                t.Completed_Date__c = System.today();
            }
        }
    }
    public static void setDefaults(List<Implementation_Task__c> tasks) {
        setDefaults(tasks, null);
    }
    public static void setDefaults(List<Implementation_Task__c> tasks, Map<Id, Implementation_Task__c> oldMpa) {
        for (Implementation_Task__c t : tasks) {
            t.Unique_Sequence__c = '' + t.Implementation_Plan__c + '-' + t.Sequence__c;
        }
    }
    public static void updatePlanDetails(List<Implementation_Task__c> tasks) {
        updatePlanDetails(tasks, null);
    }
    public static void updatePlanDetails(List<Implementation_Task__c> tasks, Map<Id, Implementation_Task__c> oldMap) {
        set<Id> plansTouched = new set<Id>();
        for (Implementation_Task__c t : tasks) {
            if (oldMap == null || t.Implementation_Plan__c != oldMap.get(t.Id).Implementation_Plan__c || t.Status__c != oldMap.get(t.Id).Status__c) {
                if (oldMap != null) plansTouched.add(oldMap.get(t.Id).Implementation_Plan__c);
                plansTouched.add(t.Implementation_Plan__c);
            }
        }
        if (!plansTouched.isEmpty()) {
	        List<Implementation_Plan__c> plansToUpdate = new List<Implementation_Plan__c>();
            for (Implementation_Plan__c ip : [select Id, Completed_Tasks__c, Total_Tasks__c, Actual_Go_Live_Date__c, (select Id, Status__c, Revenue_Recognition__c from Implementation_Task__r) from Implementation_Plan__c where Id in :plansTouched]) {
                Integer totalTasks = ip.Implementation_Task__r.size();
                Integer completedTasks = 0;
                Date actualGoLiveDate = ip.Actual_Go_Live_Date__c;
                for (Implementation_Task__c it : ip.Implementation_Task__r) {
                    if (it.Status__c == 'Complete') {
                        completedTasks++;
                        if (it.Revenue_Recognition__c == 'Software Go-Live Date' && actualGoLiveDate == null) actualGoLiveDate = System.today();
                    }
                }
                if (ip.Total_Tasks__c != totalTasks || ip.Completed_Tasks__c != completedTasks || ip.Actual_Go_Live_Date__c != actualGoLiveDate) {
                    plansToUpdate.add(new Implementation_Plan__c(
                        Id = ip.id,
                        Total_Tasks__c = totalTasks,
                        Completed_Tasks__c = completedTasks,
                        Actual_Go_Live_Date__c = actualGoLiveDate
                    ));
                }
            }
            if (!plansToUpdate.isEmpty()) update plansToUpdate;
        }
    }
    public static void copyFilesFromTemplate(List<Implementation_Task__c> plans) {
        set<Id> templateIds = new set<Id>();
        for (Implementation_Task__c ip : plans) {
            if (ip.Implementation_Task_Template__c != null) {
                templateIds.add(ip.Implementation_Task_Template__c);
            }
        }
        if (!templateIds.isEmpty()) {
            list<ContentDocumentLink> newCdls = new list<ContentDocumentLink>();
            for (ContentDocumentLink cdl : [select Id, ContentDocumentId, LinkedEntityId from ContentDocumentLink where LinkedEntityId in :templateIds]){
                for (Implementation_Task__c ip : plans) {
                    if (ip.Implementation_Task_Template__c == cdl.LinkedEntityId) {
                        newCdls.add(new ContentDocumentLink(
                            LinkedEntityId = ip.Id,
                            ShareType = 'V',
                            ContentDocumentId = cdl.ContentDocumentId
                        ));
                    }
                }
            }
            if (!newCdls.isEmpty()) insert newCdls;
        }
    }
}