force-app/main/default/objects/Keystore__c/Keystore__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Keystore</label>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Lead_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_Source__c</fullName>
    <label>Lead Sub-Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Quarterly Call</fullName>
            </value>
            <value>
                <fullName>Workshop</fullName>
            </value>
            <value>
                <fullName>Training Call</fullName>
            </value>
            <value>
                <fullName>Site Visit</fullName>
            </value>
            <value>
                <fullName>CO APAC</fullName>
            </value>
            <value>
                <fullName>CO UK</fullName>
            </value>
            <value>
                <fullName>CO NA</fullName>
            </value>
            <value>
                <fullName>CCG AU</fullName>
            </value>
            <value>
                <fullName>VetQuip AU</fullName>
            </value>
            <value>
                <fullName>VI AU</fullName>
            </value>
            <value>
                <fullName>GSS APAC</fullName>
            </value>
            <value>
                <fullName>GSS EMEA</fullName>
            </value>
            <value>
                <fullName>GSS NA</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Internal Referral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuotePdfTest.cls
/**************************************************************************************************
*** Test Class Name             : QuotePdfTest
*** Author                 	    : Santosh Kumar
*** Trigger Created Date        : 29/07/2019
*		
**************************************************************************************************/
@istest
private class QuotePdfTest {
    private static testmethod void test() {
        Keystore__c key = new Keystore__c();
        key.name = '111111';
        insert key;
        
       /* Account ac = new Account(Name = 'test');
        insert ac;*/
        Account ac =TestDataFactory.testData();

        Opportunity opp = new Opportunity(Name = 'test',LeadSource = 'Sales',Lead_Sub_Source__c = 'Inbound', StageName = 'Draft', CloseDate = System.today(), AccountId = ac.Id, Pricebook2Id = Test.getStandardPricebookId());
        insert opp;

        Quote q = new Quote(Name = 'test', OpportunityId = opp.Id, Pricebook2Id = Test.getStandardPricebookId());
        insert q;
        
        Product2 p = new Product2(IsActive = true, Name = 'test');
        insert p;
        
        PricebookEntry pe = new PricebookEntry(IsActive = true, Pricebook2Id = test.getStandardPricebookId(), UnitPrice = 1, Product2Id = p.Id);
        insert pe;

        QuoteLineItem qli = new QuoteLineItem(QuoteId = q.Id, PricebookEntryId = pe.Id, Quantity = 1, UnitPrice = 1, Product2Id = p.Id);
        insert qli;

        Test.setCurrentPage(Page.QuotePdf);
        ApexPages.currentPage().getparameters().put('id', q.Id);
        QuotePdf gsq = new QuotePdf(new ApexPages.StandardController(q));
        String s = gsq.now;
        Decimal d = gsq.groups[0].subtotal;
    }
}