force-app/main/default/objects/Account/fields/Company_Region__c.field-meta.xml
<CustomField>
    <fullName>Company_Region__c</fullName>
    <label>Company Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>US</fullName>
                <isActive>false</isActive>
                <label>US</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Converted_Date__c.field-meta.xml
<CustomField>
    <fullName>Converted_Date__c</fullName>
    <description>Account converted date</description>
    <label>Converted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Covetrus_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Covetrus_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Covetrus Customer Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Keystore__c/Keystore__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Keystore</label>
</CustomObject>

force-app/main/default/objects/Lead/fields/Lead_Interest__c.field-meta.xml
<CustomField>
    <fullName>Lead_Interest__c</fullName>
    <description>Unrestricted picklist values for this picklist field</description>
    <label>Lead Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACESoft Business Manager</fullName>
            </value>
            <value>
                <fullName>Advantage+ Software</fullName>
            </value>
            <value>
                <fullName>AHMS</fullName>
            </value>
            <value>
                <fullName>AIS</fullName>
            </value>
            <value>
                <fullName>AlisVet</fullName>
            </value>
            <value>
                <fullName>AltaPoint Veterinary Software</fullName>
            </value>
            <value>
                <fullName>Animal Intelligence</fullName>
            </value>
            <value>
                <fullName>Animana</fullName>
            </value>
            <value>
                <fullName>Ardex</fullName>
            </value>
            <value>
                <fullName>Aria</fullName>
            </value>
            <value>
                <fullName>ATSystems</fullName>
            </value>
            <value>
                <fullName>AutoTrack</fullName>
            </value>
            <value>
                <fullName>AVImark Software</fullName>
            </value>
            <value>
                <fullName>Bastet Windows</fullName>
            </value>
            <value>
                <fullName>BeeFree</fullName>
            </value>
            <value>
                <fullName>Ciderhouse</fullName>
            </value>
            <value>
                <fullName>ClienTrax</fullName>
            </value>
            <value>
                <fullName>Client Recapture</fullName>
            </value>
            <value>
                <fullName>ClinicWare</fullName>
            </value>
            <value>
                <fullName>Complete Clinic Software</fullName>
            </value>
            <value>
                <fullName>Cornerstone</fullName>
            </value>
            <value>
                <fullName>Credit Card Processing</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Customer Logic</fullName>
            </value>
            <value>
                <fullName>Data Backup</fullName>
            </value>
            <value>
                <fullName>Dunlops - Vetsys</fullName>
            </value>
            <value>
                <fullName>DVMAX Practice</fullName>
            </value>
            <value>
                <fullName>EasyVet</fullName>
            </value>
            <value>
                <fullName>EazyVetPro</fullName>
            </value>
            <value>
                <fullName>ePetHealth</fullName>
            </value>
            <value>
                <fullName>eVetPractice</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>CCRM-2124. Adding for GSS NA Sales Users</description>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Practice Management Software</fullName>
            </value>
            <value>
                <fullName>Client Communications</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Data Backup</fullName>
            </value>
            <value>
                <fullName>Credit Card Processing</fullName>
            </value>
            <value>
                <fullName>DragonFly</fullName>
            </value>
            <value>
                <fullName>Paper Products</fullName>
            </value>
            <value>
                <fullName>Licences</fullName>
            </value>
            <value>
                <fullName>Servers</fullName>
            </value>
            <value>
                <fullName>Mobile App</fullName>
            </value>
            <value>
                <fullName>Herd Health Management</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Modules</fullName>
            </value>
            <value>
                <fullName>Business Intelligence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/NA.recordType-meta.xml
<RecordType>
    <fullName>NA</fullName>
    <active>true</active>
    <businessProcess>Lead Process</businessProcess>
    <label>NA</label>
</RecordType>

force-app/main/default/objects/Lead_Assignment__c/Lead_Assignment__c.object-meta.xml
<CustomObject>
    <description>Object used to manage the Lead Assignment Rules. Sales Ops Administrators will be able to maintain the assignments within Production</description>
    <label>Lead Assignment</label>
    <nameField>
        <displayFormat>LA-{00}</displayFormat>
        <label>Lead Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Assignment__c/fields/Lead_Interest__c.field-meta.xml
<CustomField>
    <fullName>Lead_Interest__c</fullName>
    <description>Used to map to the Lead Interest of the Lead</description>
    <label>Lead Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advantage+ Software</fullName>
            </value>
            <value>
                <fullName>AVImark Software</fullName>
            </value>
            <value>
                <fullName>eVetPractice</fullName>
            </value>
            <value>
                <fullName>ImproMed Equine Software</fullName>
            </value>
            <value>
                <fullName>ImproMed Software</fullName>
            </value>
            <value>
                <fullName>Practice Management Software</fullName>
            </value>
            <value>
                <fullName>Credit Card Processing</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Sparkline</fullName>
            </value>
            <value>
                <fullName>Rapport</fullName>
            </value>
            <value>
                <fullName>Reminder Cards</fullName>
            </value>
            <value>
                <fullName>Vetstreet</fullName>
            </value>
            <value>
                <fullName>Websites</fullName>
            </value>
            <value>
                <fullName>Client Recapture</fullName>
            </value>
            <value>
                <fullName>Data Backup</fullName>
            </value>
            <value>
                <fullName>Pet ID</fullName>
            </value>
            <value>
                <fullName>Social Management</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Online Academy</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>RxWorks</fullName>
            </value>
            <value>
                <fullName>VisionVPM</fullName>
            </value>
            <value>
                <fullName>RoboVet</fullName>
            </value>
            <value>
                <fullName>Ventana</fullName>
            </value>
            <value>
                <fullName>Healthy Pet Magazine</fullName>
            </value>
            <value>
                <fullName>Healthy Pet Magazine Seasonals</fullName>
            </value>
            <value>
                <fullName>AVImark</fullName>
                <isActive>false</isActive>
                <label>AVImark</label>
            </value>
            <value>
                <fullName>ImproMed</fullName>
                <isActive>false</isActive>
                <label>ImproMed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Assignment__c/fields/Lead_Owner__c.field-meta.xml
<CustomField>
    <fullName>Lead_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Lead_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Assignment__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Practice Management Software</fullName>
            </value>
            <value>
                <fullName>Client Communication</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Data Back-up</fullName>
            </value>
            <value>
                <fullName>Credit Card Processing</fullName>
            </value>
            <value>
                <fullName>DragonFly</fullName>
            </value>
            <value>
                <fullName>Paper Products</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Assignment__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
                <label>Alabama</label>
            </value>
            <value>
                <fullName>AK</fullName>
                <label>Alaska</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Arizona</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Arkansas</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>California</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Colorado</label>
            </value>
            <value>
                <fullName>CT</fullName>
                <label>Connecticut</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Delaware</label>
            </value>
            <value>
                <fullName>DC</fullName>
                <label>District of Columbia</label>
            </value>
            <value>
                <fullName>FL</fullName>
                <label>Florida</label>
            </value>
            <value>
                <fullName>GA</fullName>
                <label>Georgia</label>
            </value>
            <value>
                <fullName>HI</fullName>
                <label>Hawaii</label>
            </value>
            <value>
                <fullName>ID</fullName>
                <label>Idaho</label>
            </value>
            <value>
                <fullName>IL</fullName>
                <label>Illinois</label>
            </value>
            <value>
                <fullName>IN</fullName>
                <label>Indiana</label>
            </value>
            <value>
                <fullName>IA</fullName>
                <label>Iowa</label>
            </value>
            <value>
                <fullName>KS</fullName>
                <label>Kansas</label>
            </value>
            <value>
                <fullName>KY</fullName>
                <label>Kentucky</label>
            </value>
            <value>
                <fullName>LA</fullName>
                <label>Louisiana</label>
            </value>
            <value>
                <fullName>ME</fullName>
                <label>Maine</label>
            </value>
            <value>
                <fullName>MD</fullName>
                <label>Maryland</label>
            </value>
            <value>
                <fullName>MA</fullName>
                <label>Massachusetts</label>
            </value>
            <value>
                <fullName>MI</fullName>
                <label>Michigan</label>
            </value>
            <value>
                <fullName>MN</fullName>
                <label>Minnesota</label>
            </value>
            <value>
                <fullName>MS</fullName>
                <label>Mississippi</label>
            </value>
            <value>
                <fullName>MO</fullName>
                <label>Missouri</label>
            </value>
            <value>
                <fullName>MT</fullName>
                <label>Montana</label>
            </value>
            <value>
                <fullName>NE</fullName>
                <label>Nebraska</label>
            </value>
            <value>
                <fullName>NV</fullName>
                <label>Nevada</label>
            </value>
            <value>
                <fullName>NH</fullName>
                <label>New Hampshire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadTriggerHelperTest.cls
/**************************************************************************************************
*** Test Class Name             : LeadTriggerHelperTest
*** Author                 	    : Santosh Kumar
*** Trigger Created Date        : 29/07/2019
*		
**************************************************************************************************/
@IsTest
public class LeadTriggerHelperTest {
   
    @IsTest
    private static void convertedDateUpdationTest() {
        List<Account> accList = new List<Account>();
        Keystore__c key = new Keystore__c();
        key.name = '1234';
        insert key;
        ID recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Covetrus Account').getRecordTypeId();
        
        
        Account acc = new Account();
        acc.RecordTypeId =recordTypeId;
        acc.Name = 'Test AU'; // Default Account
        acc.BillingCountry = 'Australia';
        acc.BillingStreet = 'Richmond';
        acc.BillingCity = 'Banglore';
        acc.BillingState = 'QLD';
        acc.BillingPostalCode = '560016';
        acc.Company_Region__c = 'APAC';
        acc.Covetrus_Customer_Number__c = '1234';
        acc.Converted_Date__c = system.today();
        acc.Phone = '9182352449';
        acc.CurrencyIsoCode = 'AUD';
        acc.ShippingCountry = 'United States';
        acc.ShippingCity = 'Mumbai';
        acc.ShippingState = 'Alabama';
        acc.ShippingStreet = 'Santhi Nagar';
        acc.ShippingPostalCode = '560068';
        accList.add(acc);
        insert accList;
        //Account acc = TestDataFactory.testdata();
        
        Lead lead = new Lead();
        lead.Status = 'New';
        lead.LastName = 'Mark';
        //lead.Product_Category__c ='Client Communications';
        lead.Country = 'United States';
        //lead.CountryCode ='US';
        lead.Street = 'Tin factory';
        lead.City = 'Banglore';
        lead.PostalCode = '560067';
        lead.State ='California';
        // lead.StateCode ='CA';
        lead.Company = 'Coreflex';
        lead.Email = 'cfs@gmail.com';
        lead.Phone ='5567687';
        insert lead;
        acc.Converted_Date__c =System.today();
        update acc;
        lead.Status ='Converted';
        update lead;
        
        
        
        database.leadConvert lc = new database.leadConvert();
        lc.setLeadId(lead.id);
        
        leadStatus convertStatus = [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true LIMIT 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        System.assert(lcr.isSuccess());
        
        
    }
  
    static testmethod void assignLeadOwnerTest(){
         User u ;
        Lead_Assignment__c leadAssgnment ;
         Lead leadRec ;
        User usr =[Select id from user where id =:Userinfo.getUserId()];
        system.runAs(usr){
            UserRole r = new UserRole(DeveloperName = 'MyCustomRole', Name = 'NA Leader');
            insert r;
            
             u = new User();
            u.ProfileId = [SELECT Id FROM Profile WHERE Name = 'GSS Sales - NA'].Id;
            U.UserRoleId = r.Id;
            u.LastName = 'last';
            u.Email = 'test1231@test.com';
            u.Username = 'test12342@test.com.' + System.currentTimeMillis();
            u.CompanyName = 'TEST';
            u.Title = 'title';
            u.Alias = 'alias';
            u.TimeZoneSidKey = 'America/Los_Angeles';
            u.EmailEncodingKey = 'UTF-8';
            u.LanguageLocaleKey = 'en_US';
            u.LocaleSidKey = 'en_US';
            Insert u;
        
       
         ID recordTypeIdNA = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('NA').getRecordTypeId();
        Id queueIDs = [Select Queue.Id, Queue.Name, Queue.Type from QueueSObject WHERE Queue.Type ='Queue' AND Queue.Name = 'GSS NA Unassigned Leads'].Queue.Id;
        leadAssgnment = new Lead_Assignment__c();
        leadAssgnment.Product_Category__c = 'Hardware';
        leadAssgnment.Lead_Interest__c = 'eVetPractice';
        leadAssgnment.State__c = 'AK';
        leadAssgnment.Lead_Owner__c =u.id;
        insert leadAssgnment; 
        
        leadRec = new Lead();
        leadRec.RecordTypeId=recordTypeIdNA;
        leadRec.Status = 'New';
        leadRec.LastName = 'Mark';
        leadRec.Country = 'United States';
        leadRec.CountryCode ='US';
        leadRec.Street = 'Tin factory';
        leadRec.City = 'Banglore';
        leadRec.PostalCode = '560067';
        leadRec.StateCode ='AK';
        leadRec.State ='Alaska';
        leadRec.Lead_Interest__c ='eVetPractice';
        leadRec.Company = 'Coreflex';
        leadRec.Email = 'cfs@gmail12378.com';
        leadRec.Phone ='5567687';
        leadRec.OwnerId =queueIDs;

        }
         system.runAs(u){ 
             leadRec.OwnerId =leadAssgnment.Lead_Owner__c;
             Insert leadRec; 
              	             
            }
    }
}