force-app/main/default/objects/Account/fields/Company_Region__c.field-meta.xml
<CustomField>
    <fullName>Company_Region__c</fullName>
    <label>Company Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>US</fullName>
                <isActive>false</isActive>
                <label>US</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Covetrus_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Covetrus_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Covetrus Customer Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_Vets__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Vets__c</fullName>
    <label>Number of Vets</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset_Record_Types__c/Asset_Record_Types__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is created to hold the data of the asset record types.</description>
    <label>Asset Record Types</label>
</CustomObject>

force-app/main/default/objects/Asset_Record_Types__c/fields/Asset_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Asset_Record_Type__c</fullName>
    <label>Asset Record Type</label>
    <length>28</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset_Record_Types__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <length>28</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>TEXT(Account.Company_Region__c )</formula>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Implementation_Plan_Template__c/Implementation_Plan_Template__c.object-meta.xml
<CustomObject>
    <label>Implementation Plan Template</label>
    <nameField>
        <label>Implementation Template</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Plan Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Implementation_Plan_Template__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Line of Business</label>
    <referenceTo>Line_of_Business__c</referenceTo>
    <relationshipLabel>Implementation Plan Template</relationshipLabel>
    <relationshipName>Implementation_Plan_Template</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Line_of_Business__c/Line_of_Business__c.object-meta.xml
<CustomObject>
    <label>Line of Business</label>
    <nameField>
        <label>Line of Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line of Businesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_of_Business__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GSS</fullName>
            </value>
            <value>
                <fullName>GPM</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>Specialty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Line_of_Business__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
                <isActive>false</isActive>
                <label>USA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Company_Region__c.field-meta.xml
<CustomField>
    <fullName>Company_Region__c</fullName>
    <formula>TEXT(Account.Company_Region__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Company Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Current_PIMS__c.field-meta.xml
<CustomField>
    <fullName>Current_PIMS__c</fullName>
    <label>Current PIMS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_Source__c</fullName>
    <label>Lead Sub-Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Quarterly Call</fullName>
            </value>
            <value>
                <fullName>Workshop</fullName>
            </value>
            <value>
                <fullName>Training Call</fullName>
            </value>
            <value>
                <fullName>Site Visit</fullName>
            </value>
            <value>
                <fullName>CO APAC</fullName>
            </value>
            <value>
                <fullName>CO UK</fullName>
            </value>
            <value>
                <fullName>CO NA</fullName>
            </value>
            <value>
                <fullName>CCG AU</fullName>
            </value>
            <value>
                <fullName>VetQuip AU</fullName>
            </value>
            <value>
                <fullName>VI AU</fullName>
            </value>
            <value>
                <fullName>GSS APAC</fullName>
            </value>
            <value>
                <fullName>GSS EMEA</fullName>
            </value>
            <value>
                <fullName>GSS NA</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Internal Referral</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Line of Business</label>
    <referenceTo>Line_of_Business__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Number_of_Vets__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Vets__c</fullName>
    <label>Number of Vets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <description>CCRM-2128 - field to map Product Category from Lead</description>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Practice Management Software</fullName>
            </value>
            <value>
                <fullName>Client Communications</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Data Backup</fullName>
            </value>
            <value>
                <fullName>Credit Card Processing</fullName>
            </value>
            <value>
                <fullName>DragonFly</fullName>
            </value>
            <value>
                <fullName>Paper Products</fullName>
            </value>
            <value>
                <fullName>Licences</fullName>
            </value>
            <value>
                <fullName>Servers</fullName>
            </value>
            <value>
                <fullName>Mobile App</fullName>
            </value>
            <value>
                <fullName>Herd Health Management</fullName>
            </value>
            <value>
                <fullName>Integrations</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Modules</fullName>
            </value>
            <value>
                <fullName>Business Intelligence</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Surgical_Caseload_Revenue_Contribution__c.field-meta.xml
<CustomField>
    <fullName>Surgical_Caseload_Revenue_Contribution__c</fullName>
    <label>Surgical Caseload Revenue Contribution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Less than 25%</fullName>
            </value>
            <value>
                <fullName>Between 25% and 50%</fullName>
            </value>
            <value>
                <fullName>Greater than 50%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Technology.recordType-meta.xml
<RecordType>
    <fullName>Technology</fullName>
    <active>true</active>
    <businessProcess>Technology</businessProcess>
    <label>Technology</label>
</RecordType>

force-app/main/default/objects/Opportunity_Pricebook__c/Opportunity_Pricebook__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is created to hold the data of the price book along with the  related Account and LOM attributes.</description>
    <label>Opportunity Pricebook</label>
</CustomObject>

force-app/main/default/objects/Opportunity_Pricebook__c/fields/Currency_Code__c.field-meta.xml
<CustomField>
    <fullName>Currency_Code__c</fullName>
    <description>This field is to store the currency code of the Opportunity</description>
    <label>Currency Code</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Pricebook__c/fields/Line_Of_Business_Type__c.field-meta.xml
<CustomField>
    <fullName>Line_Of_Business_Type__c</fullName>
    <label>Line Of Business Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Pricebook__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <description>This field is to store the value of the Price book</description>
    <label>Price Book</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Do_Not_Create_Asset__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Create_Asset__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicator to create an asset or not CCRM-58</description>
    <label>Do Not Create Asset</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Implementation_Plan_Template__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Plan_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Implementation Plan Template</label>
    <referenceTo>Implementation_Plan_Template__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GSS</fullName>
            </value>
            <value>
                <fullName>GPM</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>All Regions</fullName>
            </value>
            <value>
                <fullName>US</fullName>
                <isActive>false</isActive>
                <label>US</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Hardware.recordType-meta.xml
<RecordType>
    <fullName>Hardware</fullName>
    <active>true</active>
    <label>Hardware</label>
</RecordType>

force-app/main/default/classes/OpportunityTriggerTest.cls
/**************************************************************************************************
*** Test Class Name             : OpportunityTriggerTest
*** Author                 	    : Sreenath Dhanireddy
*** Class Created Date        	: 29/07/2019
*		
**************************************************************************************************/
@isTest
public class OpportunityTriggerTest {
    
    static testmethod void updateOpportunityPriceBookTest(){
        
        Account acc =TestDataFactory.testData();
        
        Map<ID,string> accMap = new Map<ID,string>();
        accMap.put(acc.ID, acc.BillingCountry);
        
        Pricebook2 pb2 = new Pricebook2(Name = 'GSS AU', IsActive = True);
        insert pb2;
    
        Line_Of_Business__c lob = new Line_Of_Business__c(Name = 'GSS Test', Line_of_Business__c = 'GSS');
        insert lob;
       
        List<Opportunity_Pricebook__c> oppPbList = new List<Opportunity_Pricebook__c>();
        Opportunity_Pricebook__c oppPbAU = new Opportunity_Pricebook__c();
        oppPbAU.Name = 'Australia';
        oppPbAU.Currency_Code__c = 'AUD';
        oppPbAU.Line_Of_Business_Type__c = 'GSS';
        oppPbAU.Price_Book__c = 'GSS AU';
        insert oppPbAU;
        oppPbList.add(oppPbAU);
        
        Opportunity_Pricebook__c oppPbNZ = new Opportunity_Pricebook__c();
        oppPbNZ.Name = 'New Zealand';
        oppPbNZ.Currency_Code__c = 'NZD';
        oppPbNZ.Line_Of_Business_Type__c = 'GSS';
        oppPbNZ.Price_Book__c = 'GSS NZ';
        insert oppPbNZ;
        oppPbList.add(oppPbNZ);
	
        Map<ID,string> lobMap = new Map<ID,string>();
        lobMap.put(lob.ID, lob.Line_of_Business__c);
        
        User user = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'last',
            Email = 'puser000@cfs.com',
            Username = 'puser000@cfs.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
        );
        insert user;
        VIOpportunity__c viOpp = new VIOpportunity__c();
        viOpp.SetupOwnerId = user.id;
        insert viOpp;
        
        string recordtypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('VI Opportunity').getRecordTypeId();
        
        List<Opportunity> oppList =new List<opportunity>();
        Opportunity opp = new Opportunity();
        opp.AccountID = acc.ID;
        opp.CurrencyIsoCode = 'AUD';
        opp.Name = 'Covertus Opportunity';
        opp.Pricebook2ID = pb2.ID;
        opp.Line_of_Business__c = lob.ID;
        opp.CloseDate =  system.today();
        opp.StageName = 'Qualification';
        opp.LeadSource = 'Sales';
        opp.Lead_Sub_Source__c = 'Inbound';
        opp.Type = 'New Customer';
        opp.Surgical_Caseload_Revenue_Contribution__c = 'Less than 25%';
        opp.OwnerId = viOpp.SetupOwnerId;
        insert opp;
        oppList.add(opp);
       
    }
    
    static testmethod void updateOpportunityPriceBookWithCountryTest(){
        
        Keystore__c key = new Keystore__c();
        key.Name = '0000000';
        insert key;
        
        Account acc =TestDataFactory.testData();
        
        Account accAsia = new Account();
        accAsia.Name = 'Asia';
        accAsia.BillingCountry = 'Australia';
        accAsia.Company_Region__c = 'APAC';
        accAsia.Covetrus_Customer_Number__c = '12345';
        
        Map<ID,string> accMap = new Map<ID,string>();
        accMap.put(acc.ID, acc.BillingCountry);
        
        Pricebook2 pb2 = new Pricebook2(Name = 'GSS AU', IsActive = True);
        insert pb2;
        
        Pricebook2 pricebook2Asia = new Pricebook2(Name = 'GSS Asia', IsActive = True);
        insert pricebook2Asia;

        List<Opportunity_Pricebook__c> oppPbList = new List<Opportunity_Pricebook__c>();
        Opportunity_Pricebook__c oppPbAU = new Opportunity_Pricebook__c();
        oppPbAU.Name = 'Australia';
        oppPbAU.Currency_Code__c = 'AUD';
        oppPbAU.Line_Of_Business_Type__c = 'GSS';
        oppPbAU.Price_Book__c = 'GSS AU';
        insert oppPbAU;
        oppPbList.add(oppPbAU);
        
        Opportunity_Pricebook__c oppPbNZ = new Opportunity_Pricebook__c();
        oppPbNZ.Name = 'New Zealand';
        oppPbNZ.Currency_Code__c = 'NZD';
        oppPbNZ.Line_Of_Business_Type__c = 'GSS';
        oppPbNZ.Price_Book__c = 'GSS NZ';
        insert oppPbNZ;
        oppPbList.add(oppPbNZ);
		
        User user = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'last',
            Email = 'puser000@cfs.com',
            Username = 'puser000@cfs.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
        );
        insert user;
        VIOpportunity__c viOpp = new VIOpportunity__c();
        viOpp.SetupOwnerId = user.id;
        insert viOpp;
        
        string recordtypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('VI Opportunity').getRecordTypeId();
        
        List<Opportunity> oppList =new List<opportunity>();
        Opportunity opp = new Opportunity();
        opp.AccountID = acc.ID;
        opp.CurrencyIsoCode = 'AUD';
        opp.Name = 'Covertus Opportunity';
        opp.Pricebook2ID = pb2.ID;
        opp.CloseDate =  system.today();
        opp.StageName = 'Qualification';
        opp.LeadSource = 'Sales';
        opp.Lead_Sub_Source__c = 'Inbound';
        opp.Type = 'New Customer';
        opp.Surgical_Caseload_Revenue_Contribution__c = 'Less than 25%';
        opp.OwnerId = viOpp.SetupOwnerId;
        insert opp;
        oppList.add(opp);
       
        Opportunity oppAsia = new Opportunity();
        oppAsia.AccountID = accAsia.ID;
        oppAsia.Name = 'Opportunity Asia';
        oppAsia.CurrencyIsoCode = 'USD';
        oppAsia.Pricebook2ID = pricebook2Asia.ID;
        oppAsia.CloseDate =  system.today();
        oppAsia.StageName = 'Qualification';
        oppAsia.LeadSource = 'Sales';
        oppAsia.Lead_Sub_Source__c = 'Inbound';
        oppAsia.Type = 'New Customer';
        oppAsia.Surgical_Caseload_Revenue_Contribution__c = 'Less than 25%';
        insert oppAsia;
        oppList.add(oppAsia);

    }
    
    static testmethod void opportunityPriceBookWithoutCountryTest(){
        
        Keystore__c key = new Keystore__c();
        key.Name = '0000000';
        insert key;

        Account acc =TestDataFactory.testData();
        
        Account accAsia = new Account(Name = 'Asia big', Company_Region__c = 'APAC', Covetrus_Customer_Number__c = '12346');
        accAsia.ShippingCity ='WaShington';
        accAsia.ShippingCountry ='United States';
        //accAsia.ShippingPostalCode='303099';
        accAsia.ShippingState ='WaShington';
        accAsia.ShippingStreet ='36 - 66 ST. ALBERT TRAIL';
        accAsia.phone ='32652534';
        accAsia.BillingCity ='WaShington';
        accAsia.BillingCountry ='United States';
        accAsia.Billingpostalcode ='303099';
        accAsia.BillingState ='WaShington';
        accAsia.BillingStreet='36 - 66 ST. ALBERT TRAIL';
        accAsia.CurrencyIsoCode ='USD';
        insert accAsia;
 
        Map<ID,string> accMap = new Map<ID,string>();
        accMap.put(acc.ID, acc.BillingCountry);
        
        Pricebook2 pb2 = new Pricebook2(Name = 'GSS AU', IsActive = True);
        insert pb2;
     
        Pricebook2 pricebook2Asia = new Pricebook2(Name = 'GSS Asia', IsActive = True);
        insert pricebook2Asia;
        
        Line_Of_Business__c lob = new Line_Of_Business__c(Name = 'GSS Test', Line_of_Business__c = 'GSS');
        insert lob;
       
        List<Opportunity_Pricebook__c> oppPbList = new List<Opportunity_Pricebook__c>();
        Opportunity_Pricebook__c oppPbAU = new Opportunity_Pricebook__c();
        oppPbAU.Name = 'Australia';
        oppPbAU.Currency_Code__c = 'NZD';
        oppPbAU.Line_Of_Business_Type__c = 'GSS';
        oppPbAU.Price_Book__c = 'GSS AU';
        insert oppPbAU;
        oppPbList.add(oppPbAU);
        
        Opportunity_Pricebook__c oppPbNZ = new Opportunity_Pricebook__c();
        oppPbNZ.Name = 'New Zealand';
        oppPbNZ.Currency_Code__c = '';
        oppPbNZ.Line_Of_Business_Type__c = 'GSS';
        oppPbNZ.Price_Book__c = 'GSS NZ';
        oppPbNZ.Country__c = 'USA';
        insert oppPbNZ;
        oppPbList.add(oppPbNZ);
	
        Map<ID,string> lobMap = new Map<ID,string>();
        lobMap.put(lob.ID, lob.Line_of_Business__c);
        
        User user = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'last',
            Email = 'puser000@cfs.com',
            Username = 'puser000@cfs.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
        );
        insert user;
        VIOpportunity__c viOpp = new VIOpportunity__c();
        viOpp.SetupOwnerId = user.id;
        insert viOpp;
        
        string recordtypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('VI Opportunity').getRecordTypeId();
        
        List<Opportunity> oppList =new List<opportunity>();
        Opportunity opp = new Opportunity();
        opp.AccountID = acc.ID;
        opp.CurrencyIsoCode = 'AUD';
        opp.Name = 'Covertus Opportunity';
        opp.Pricebook2ID = pb2.ID;
        opp.Line_of_Business__c = lob.ID;
        opp.CloseDate =  system.today();
        opp.StageName = 'Qualification';
        opp.LeadSource = 'Sales';
        opp.Lead_Sub_Source__c = 'Inbound';
        opp.Type = 'New Customer';
        opp.OwnerId = viOpp.SetupOwnerId;
        opp.RecordTypeId = recordtypeId;
        opp.Surgical_Caseload_Revenue_Contribution__c = 'Less than 25%';
        insert opp;
        oppList.add(opp);
        
        Opportunity oppAsia = new Opportunity();
        oppAsia.AccountID = accAsia.ID;
        oppAsia.Name = 'Opportunity Asia';
        oppAsia.CurrencyIsoCode = 'USD';
        oppAsia.Pricebook2ID = pricebook2Asia.ID;
        oppAsia.Line_of_Business__c = lob.ID;
        oppAsia.CloseDate =  system.today();
        oppAsia.StageName = 'Qualification';
        oppAsia.LeadSource = 'Sales';
        oppAsia.Lead_Sub_Source__c = 'Inbound';
        oppAsia.Type = 'New Customer';
        oppAsia.Surgical_Caseload_Revenue_Contribution__c = 'Less than 25%';
        insert oppAsia;
        oppList.add(oppAsia);
    }
    
    static testmethod void assetCreationTest(){
        
        Map<String, String> asstRecMap = new Map<String, String>();
        Asset_Record_Types__c asstRecType = new Asset_Record_Types__c();
        asstRecType.Name = 'Hardware';
        asstRecType.Product_Category__c = 'Hardware';
        asstRecType.Asset_Record_Type__c = 'Hardware';
        Insert asstRecType;
        
        asstRecMap.put(asstRecType.Name, asstRecType.Asset_Record_Type__c);
		//System.debug('asstRecMap-->'+asstRecMap);
        Keystore__c key = new Keystore__c();
        key.Name = '0000000';
        insert key;
        //Default Account for Line of Business
		List<Account> AccountList = new List<Account>();
        Account acc =TestDataFactory.testData();
        AccountList.add(acc);
        
        contact con =new contact();
        con.lastname ='Test';
        insert con;

        Pricebook2 pb2 = new Pricebook2(Name = 'GSS NA', IsActive = True, CurrencyIsoCode = 'AUD');
        insert pb2;
  		
        List<Line_of_Business__c> LOBList = new List<Line_of_Business__c>();
        Line_of_Business__c lob = new Line_of_Business__c();
        lob.Name = 'Test';
        lob.Line_of_Business__c ='GSS';
        lob.Region__c ='NA';
        //LOBList.add(lob);
        
        insert lob;
        
          Implementation_Plan_Template__c  impPlanTemp = new Implementation_Plan_Template__c(Name ='Test',Line_of_Business__c =lob.id);
           insert impPlanTemp;
        
        List<Product2> ProductList = new List<Product2>();
        Product2 prod = new Product2();
        prod.Name = 'TestProduct';
        prod.IsActive = True;
        prod.Region__c = 'APAC';
        prod.Line_of_Business__c = 'GSS';
        prod.Family = 'Hardware';
        prod.CurrencyIsoCode = 'AUD';
        prod.ProductCode = 'RXTest';
        prod.Do_Not_Create_Asset__c = False;
        prod.Implementation_Plan_Template__c =impPlanTemp.id;
        insert prod;

        
        List<PriceBookEntry> PriceBookEntryList = new List<PriceBookEntry>();
        PriceBookEntry pbeStandard = new PriceBookEntry(UnitPrice = 1.5, UseStandardPrice = false, IsActive = true, Product2ID = prod.ID, PriceBook2ID = System.Test.getStandardPricebookID());
        pbeStandard.CurrencyIsoCode = 'AUD';
        PriceBookEntryList.add(pbeStandard);
        
        PriceBookEntry pbeCustom = new PriceBookEntry(UnitPrice = 1.5, UseStandardPrice = false, IsActive = true, Product2ID = prod.ID, PriceBook2ID = pb2.ID);
        pbeCustom.CurrencyIsoCode = 'AUD';
        PriceBookEntryList.add(pbeCustom);
        
        insert PriceBookEntryList;
        
        User user = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'last',
            Email = 'puser000@gmail.com',
            Username = 'puser000@gmail.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US'
        );
        insert user;
        VIOpportunity__c viOpp = new VIOpportunity__c();
        viOpp.SetupOwnerId = user.id;
        insert viOpp;
        
        string recordtypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Technology').getRecordTypeId();
        
        List<Opportunity> OpportunityList = new List<Opportunity>();
        Opportunity opp = new Opportunity();
        opp.AccountID = acc.ID;
        opp.CurrencyIsoCode = 'AUD';
        opp.Name = 'Covertus Opportunity';
        opp.Pricebook2ID = pb2.ID;
        opp.Line_of_Business__c = lob.ID;
        opp.CloseDate =  system.today();
        opp.StageName = 'Qualification';
        opp.LeadSource = 'Sales';
        opp.Lead_Sub_Source__c = 'Inbound';
        opp.Type = 'New Customer';
        opp.Amount = 10;
        opp.Number_of_Vets__c = 2;
        opp.Current_PIMS__c = 'Test';
        opp.Number_of_Faxes_Week__c = 5;
        opp.Competitive_ProvIDer__c = 'Test';
        opp.Number_of_Client_E_mails__c = 4;
        opp.Timeline_for_Decision__c = system.today();
        opp.Demo_Completed_Date__c = system.today();
        opp.Date_Paperwork_Sent__c = system.today();
        opp.Date_Paperwork_Received__c = system.today();
        opp.Decision_Maker_Present__c = True;
        opp.Decision_Maker_Agreement__c = True;
        opp.Surgical_Caseload_Revenue_Contribution__c = 'Less than 25%';
        opp.RecordTypeId = recordtypeId;
        opp.OwnerId = viOpp.SetupOwnerId;
        OpportunityList.add(opp);
        
        insert OpportunityList;
       
        
        List<Opportunitylineitem> OpportunitylineitemList = new List<Opportunitylineitem>();
        Opportunitylineitem oppLineItem = new Opportunitylineitem();
        oppLineItem.Description='test';
        oppLineItem.OpportunityID = OpportunityList[0].ID;
        oppLineItem.Product2ID=prod.ID;
        oppLineItem.PricebookEntryID = pbeCustom.ID;
        oppLineItem.Quantity =2;
        oppLineItem.UnitPrice = 1.5;
        OpportunitylineitemList.add(oppLineItem);
        insert OpportunitylineitemList;
        
        Quote qt = new Quote();
        qt.name ='Test Quote';
        qt.OpportunityId =OpportunityList[0].Id;
        qt.ContactId =con.id;
        qt.BillingCity ='Atlanta';
        qt.BillingStreet = 'Test 1123';
        qt.BillingPostalCode ='30309';
        qt.ShippingCity ='Atlanta';
        qt.ShippingStreet = 'Test 1123';
        qt.ShippingPostalCode ='303091';
        qt.Description ='Test Descriptioon';
        qt.Pricebook2Id =pb2.ID;
        qt.BillingName ='Test';
        qt.Status = 'Accepted';
        insert qt;
        
        QuoteLineItem qutLineItem = new QuoteLineItem();
        qutLineItem.Description ='Test description';
        qutLineItem.PricebookEntryId =pbeCustom.ID;
        qutLineItem.Product2Id =prod.ID;
        qutLineItem.Quantity =2;
        qutLineItem.UnitPrice=1.5;
        qutLineItem.LineNumber__c =2;
        qutLineItem.NestedLineNumber__c ='1T2T';
        qutLineItem.RecordId__c ='TEST'; 
        qutLineItem.QuoteId=qt.id;
        insert qutLineItem;
        
        opp.SyncedQuoteId = qt.Id;
        update opp;
         
        opp.StageName ='Closed Won';
        update opp;
    }
    
    
    
}