force-app/main/default/objects/Account/fields/Company_Region__c.field-meta.xml
<CustomField>
    <fullName>Company_Region__c</fullName>
    <label>Company Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>US</fullName>
                <isActive>false</isActive>
                <label>US</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Covetrus_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Covetrus_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>Covetrus Customer Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CatchAndPublishExceptionEventTest.cls
@istest
public class CatchAndPublishExceptionEventTest {
      public static Testmethod void testexeception(){
       Contact acc1 =new Contact();
       acc1.LastName='test';
          //acc1.Company_Region__c ='APAC';
          acc1.CurrencyIsoCode ='USD';
         // acc1.Covetrus_Customer_Number__c ='123456';
       //acc1.Test_Valid__c=true;
       insert acc1;
        Profile pro = [SELECT Id FROM Profile WHERE Name='System Administrator'];
       
      
          User usr = new User(Alias = 'test', Email='reassignmenttrigger@testorg.com',
                            EmailEncodingKey='UTF-8', LastName='assignment', LanguageLocaleKey='en_US',
                            LocaleSidKey='en_US',ProfileId = pro.Id,TimeZoneSidKey='America/Los_Angeles', UserName='reassignment@testorg.com',isActive=true);
       
        insert usr;
        String userID=usr.Id;    
        
       List<contact> rec= new List<contact>();
      rec.add(acc1);
       system.debug('rec'+rec);
          
       try{    
           account acc =new account();
           INSERT ACC;
       }catch(exception e){
       CatchAndPublishExceptionEvent.getExceptionDetails(e, 'userID', rec, acc1 ,null);
      
       }
    }
    
    
}