force-app/main/default/objects/Account/fields/Converted_Date__c.field-meta.xml
<CustomField>
    <fullName>Converted_Date__c</fullName>
    <description>Account converted date</description>
    <label>Converted Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Interest__c.field-meta.xml
<CustomField>
    <fullName>Lead_Interest__c</fullName>
    <description>Unrestricted picklist values for this picklist field</description>
    <label>Lead Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACESoft Business Manager</fullName>
            </value>
            <value>
                <fullName>Advantage+ Software</fullName>
            </value>
            <value>
                <fullName>AHMS</fullName>
            </value>
            <value>
                <fullName>AIS</fullName>
            </value>
            <value>
                <fullName>AlisVet</fullName>
            </value>
            <value>
                <fullName>AltaPoint Veterinary Software</fullName>
            </value>
            <value>
                <fullName>Animal Intelligence</fullName>
            </value>
            <value>
                <fullName>Animana</fullName>
            </value>
            <value>
                <fullName>Ardex</fullName>
            </value>
            <value>
                <fullName>Aria</fullName>
            </value>
            <value>
                <fullName>ATSystems</fullName>
            </value>
            <value>
                <fullName>AutoTrack</fullName>
            </value>
            <value>
                <fullName>AVImark Software</fullName>
            </value>
            <value>
                <fullName>Bastet Windows</fullName>
            </value>
            <value>
                <fullName>BeeFree</fullName>
            </value>
            <value>
                <fullName>Ciderhouse</fullName>
            </value>
            <value>
                <fullName>ClienTrax</fullName>
            </value>
            <value>
                <fullName>Client Recapture</fullName>
            </value>
            <value>
                <fullName>ClinicWare</fullName>
            </value>
            <value>
                <fullName>Complete Clinic Software</fullName>
            </value>
            <value>
                <fullName>Cornerstone</fullName>
            </value>
            <value>
                <fullName>Credit Card Processing</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Customer Logic</fullName>
            </value>
            <value>
                <fullName>Data Backup</fullName>
            </value>
            <value>
                <fullName>Dunlops - Vetsys</fullName>
            </value>
            <value>
                <fullName>DVMAX Practice</fullName>
            </value>
            <value>
                <fullName>EasyVet</fullName>
            </value>
            <value>
                <fullName>EazyVetPro</fullName>
            </value>
            <value>
                <fullName>ePetHealth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/NA.recordType-meta.xml
<RecordType>
    <fullName>NA</fullName>
    <active>true</active>
    <businessProcess>Lead Process</businessProcess>
    <label>NA</label>
</RecordType>

force-app/main/default/objects/Lead_Assignment__c/Lead_Assignment__c.object-meta.xml
<CustomObject>
    <description>Object used to manage the Lead Assignment Rules. Sales Ops Administrators will be able to maintain the assignments within Production</description>
    <label>Lead Assignment</label>
    <nameField>
        <displayFormat>LA-{00}</displayFormat>
        <label>Lead Assignment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Assignment__c/fields/Lead_Interest__c.field-meta.xml
<CustomField>
    <fullName>Lead_Interest__c</fullName>
    <description>Used to map to the Lead Interest of the Lead</description>
    <label>Lead Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advantage+ Software</fullName>
            </value>
            <value>
                <fullName>AVImark Software</fullName>
            </value>
            <value>
                <fullName>eVetPractice</fullName>
            </value>
            <value>
                <fullName>ImproMed Equine Software</fullName>
            </value>
            <value>
                <fullName>ImproMed Software</fullName>
            </value>
            <value>
                <fullName>Practice Management Software</fullName>
            </value>
            <value>
                <fullName>Credit Card Processing</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Sparkline</fullName>
            </value>
            <value>
                <fullName>Rapport</fullName>
            </value>
            <value>
                <fullName>Reminder Cards</fullName>
            </value>
            <value>
                <fullName>Vetstreet</fullName>
            </value>
            <value>
                <fullName>Websites</fullName>
            </value>
            <value>
                <fullName>Client Recapture</fullName>
            </value>
            <value>
                <fullName>Data Backup</fullName>
            </value>
            <value>
                <fullName>Pet ID</fullName>
            </value>
            <value>
                <fullName>Social Management</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Online Academy</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>RxWorks</fullName>
            </value>
            <value>
                <fullName>VisionVPM</fullName>
            </value>
            <value>
                <fullName>RoboVet</fullName>
            </value>
            <value>
                <fullName>Ventana</fullName>
            </value>
            <value>
                <fullName>Healthy Pet Magazine</fullName>
            </value>
            <value>
                <fullName>Healthy Pet Magazine Seasonals</fullName>
            </value>
            <value>
                <fullName>AVImark</fullName>
                <isActive>false</isActive>
                <label>AVImark</label>
            </value>
            <value>
                <fullName>ImproMed</fullName>
                <isActive>false</isActive>
                <label>ImproMed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Assignment__c/fields/Lead_Owner__c.field-meta.xml
<CustomField>
    <fullName>Lead_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Lead_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Assignment__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
                <label>Alabama</label>
            </value>
            <value>
                <fullName>AK</fullName>
                <label>Alaska</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Arizona</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Arkansas</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>California</label>
            </value>
            <value>
                <fullName>CO</fullName>
                <label>Colorado</label>
            </value>
            <value>
                <fullName>CT</fullName>
                <label>Connecticut</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Delaware</label>
            </value>
            <value>
                <fullName>DC</fullName>
                <label>District of Columbia</label>
            </value>
            <value>
                <fullName>FL</fullName>
                <label>Florida</label>
            </value>
            <value>
                <fullName>GA</fullName>
                <label>Georgia</label>
            </value>
            <value>
                <fullName>HI</fullName>
                <label>Hawaii</label>
            </value>
            <value>
                <fullName>ID</fullName>
                <label>Idaho</label>
            </value>
            <value>
                <fullName>IL</fullName>
                <label>Illinois</label>
            </value>
            <value>
                <fullName>IN</fullName>
                <label>Indiana</label>
            </value>
            <value>
                <fullName>IA</fullName>
                <label>Iowa</label>
            </value>
            <value>
                <fullName>KS</fullName>
                <label>Kansas</label>
            </value>
            <value>
                <fullName>KY</fullName>
                <label>Kentucky</label>
            </value>
            <value>
                <fullName>LA</fullName>
                <label>Louisiana</label>
            </value>
            <value>
                <fullName>ME</fullName>
                <label>Maine</label>
            </value>
            <value>
                <fullName>MD</fullName>
                <label>Maryland</label>
            </value>
            <value>
                <fullName>MA</fullName>
                <label>Massachusetts</label>
            </value>
            <value>
                <fullName>MI</fullName>
                <label>Michigan</label>
            </value>
            <value>
                <fullName>MN</fullName>
                <label>Minnesota</label>
            </value>
            <value>
                <fullName>MS</fullName>
                <label>Mississippi</label>
            </value>
            <value>
                <fullName>MO</fullName>
                <label>Missouri</label>
            </value>
            <value>
                <fullName>MT</fullName>
                <label>Montana</label>
            </value>
            <value>
                <fullName>NE</fullName>
                <label>Nebraska</label>
            </value>
            <value>
                <fullName>NV</fullName>
                <label>Nevada</label>
            </value>
            <value>
                <fullName>NH</fullName>
                <label>New Hampshire</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadTriggerHelper.cls
/*****************************************************************************************************
*** Class Name               :  LeadTriggerHelper
*** Class Description        :  Class for handling the processing of leads.
*** Author                   :  Will Craig
*** Class Created Date       :  11/5/2019
*       Modified Date        :  01/Jan/2020
*       Modified By          :  Vinay K
******************************************************************************************************/

public class LeadTriggerHelper {
    
    /*************************************************************************************************************
*** Method Name             : assignLeadOwner
*** Method Description      : 1. Lead Assignment record where the State and Lead Interest matches what is 
listed in the lead
2. Once it finds the record, it should use the id of the user in the Lead
Owner field of that record and then go back to the Lead and update the 
owner of the Lead to be what was in the Lead Assignment record
3. If no match is found, assign lead to the GSS NA Unassigned Leads queue
***************************************************************************************************************/
    public static void assignLeadOwner(List < Lead > leadList) {
        //Start of CCRM-3180
        List < string > leadInterestList = new List < string > ();
        //End of CCRM-3180
        List < string > stateList = new List < string > ();
        ID leadRecTypeId = Schema.Sobjecttype.Lead.getRecordTypeInfosByName().get('NA').getRecordTypeId();
        Id queueID = [Select Queue.Id, Queue.Name, Queue.Type from QueueSObject WHERE Queue.Type = 'Queue'
                      AND Queue.Name = 'GSS NA Unassigned Leads'
                     ].Queue.Id;
        Set < ID > currentRoleIds = (new Map < Id, UserRole > ([SELECT id, Name FROM UserRole
                                                                WHERE Name like '%NA%'
                                                                AND(NOT Name LIKE '%NA Sales Rep%')
                                                                AND(NOT Name LIKE '%APAC%') AND(NOT Name LIKE '%EMEA%')
                                                                 //Start of CCRM-3387
                                                                AND(NOT Name LIKE '%GPM NA%') 
                                                                 //End of CCRM-3387
                                                               ])).keySet();
        try {
            for (Lead ld: leadList) {
                if (ld.RecordTypeId == leadRecTypeId) {
                    //Start of CCRM-3477
                    if (currentRoleIds.contains(UserInfo.getUserRoleId())) {
                        ld.ownerId = queueID;
                    }
                    if (ld.ownerId == queueID) {
                        //End of CCRM-3477

                        leadInterestList.add(ld.Lead_Interest__c);
                        stateList.add(ld.StateCode);
                    }
                }
            }
            if (!leadInterestList.isEmpty() && !stateList.isEmpty()) {
                //Start of CCRM-3180
                List < Lead_Assignment__c > laList = [SELECT Id, OwnerId, Lead_Interest__c, Lead_Owner__c, State__c FROM Lead_Assignment__c
                                                      WHERE Lead_Interest__c IN: leadInterestList AND State__c IN: stateList
                                                     ];
               system.debug('enter');
                //End of CCRM-3180
                for (Lead ld: leadList) {
                    if (ld.OwnerId == queueID && ld.RecordTypeId == leadRecTypeId) {
                        for (Lead_Assignment__c la: laList) {
                            
                            if (ld.Lead_Interest__c == la.Lead_Interest__c && ld.StateCode == la.State__c) {
                                   system.debug('enter'); 
                                ld.OwnerId = la.Lead_Owner__c;
                                break;
                            }
                        }
                    }
                }
            }
        } catch (Exception e) {
            String inputFromMethodParameters = CaptureInputFromApexMethod.captureAndReturnInput(string.valueOf('List<Lead>'), string.valueOf(leadList), null, null, null, null, null, null, null, null);
            CatchAndPublishExceptionEvent.getExceptionDetails(e, UserInfo.getUserId(), null, null, inputFromMethodParameters);
        }
    }
    /*************************************************************************************************************
*** Method Name             : convertedDateUpdation
*** Method Description      : After Lead is converted to Account the Converted Date will be update to today date 
***************************************************************************************************************/
    public static void convertedDateUpdation(List < Lead > leadList) {
        List < Account > accList = new List < Account > ();
        Set < ID > leadIdSet = new Set < ID > ();
        
        for (Lead lead: leadList) {
            if (lead.IsConverted) {
                leadIdSet.add(lead.ConvertedAccountId);
            }
            List < Account > newAccList = [SELECT ID, Name, Converted_Date__c FROM Account WHERE Account.Id =: leadIdSet];
            for (Account acc: newAccList) {
                if ((acc.Converted_Date__c == null)) {
                    acc.Converted_Date__c = system.today();
                    accList.add(acc);
                }
            }
            //Start of CCRM-3149
            If(accList.Size() > 0) {
                update accList;
                //End of CCRM-3149
            }
            
        }
    }
}