force-app/main/default/objects/Account/fields/Integration_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Integration_Requested_Date__c</fullName>
    <label>Integration Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Computer_Name__c.field-meta.xml
<CustomField>
    <fullName>Computer_Name__c</fullName>
    <description>Name or identifier for the computer that has the software installed on it.CCRM-83</description>
    <label>Computer Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Demo_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Demo_Expiry_Date__c</fullName>
    <label>Demo Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Integration_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>Integration_Requested_Date__c</fullName>
    <label>Integration Requested Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Asset/fields/License_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>License_Expiry_Date__c</fullName>
    <description>For licensed software systems, this will be the recorded date for the license.  This will normally be set during workflow performance or with a renewal.CCRM-83</description>
    <label>License Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Line of Business</label>
    <referenceTo>Line_of_Business__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <formula>Line_of_Business__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LOB</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Update_Date__c.field-meta.xml
<CustomField>
    <fullName>Update_Date__c</fullName>
    <description>Asset Data will be sent to Boomi as soon as this field is updated.</description>
    <label>Update Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <description>This field contains system version number of the software</description>
    <label>Version</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Hardware.recordType-meta.xml
<RecordType>
    <fullName>Hardware</fullName>
    <active>true</active>
    <description>This asset category describes the hardware assets sold to an Animal Care Business (Clinic) that support or are used in conjunction with a sold software asset.</description>
    <label>Hardware</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Software.recordType-meta.xml
<RecordType>
    <fullName>Software</fullName>
    <active>true</active>
    <description>This asset category describes the Practice management software to include the configuration of that software (modules and versions) that has been sold to a particular Animal Care Business (Clinic)</description>
    <label>Software</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Support.recordType-meta.xml
<RecordType>
    <fullName>Support</fullName>
    <active>true</active>
    <description>This asset category describes maintenance support agreements for Practice Management or Practice Performance assets that are provided.</description>
    <label>Support</label>
</RecordType>

force-app/main/default/objects/Line_of_Business__c/Line_of_Business__c.object-meta.xml
<CustomObject>
    <label>Line of Business</label>
    <nameField>
        <label>Line of Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line of Businesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_of_Business__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GSS</fullName>
            </value>
            <value>
                <fullName>GPM</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>Specialty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Line_of_Business__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
                <isActive>false</isActive>
                <label>USA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Bundle_Key__c.field-meta.xml
<CustomField>
    <fullName>Bundle_Key__c</fullName>
    <label>Bundle Key</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GSS</fullName>
            </value>
            <value>
                <fullName>GPM</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>All Regions</fullName>
            </value>
            <value>
                <fullName>US</fullName>
                <isActive>false</isActive>
                <label>US</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Hardware.recordType-meta.xml
<RecordType>
    <fullName>Hardware</fullName>
    <active>true</active>
    <label>Hardware</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Software.recordType-meta.xml
<RecordType>
    <fullName>Software</fullName>
    <active>true</active>
    <label>Software</label>
</RecordType>

force-app/main/default/classes/AssetTriggerHelperTest.cls
/****************************************************************************************************************************
*** Class Name          	 :  AssetTriggerHelperTest 
*** Author                   :  Nagarjuna G
*** Class Created Date     	 :	11/12/2019
*		Modified Date        :	
*		Modified By          :  
******************************************************************************************************************************/
@isTest
public class AssetTriggerHelperTest {
    public static testMethod void createChildAssets(){
        Account acc =TestDataFactory.testData();

        Product2 testProd = new Product2();
        testProd.Name = 'sampleProd';
       	testProd.Region__c = 'APAC';
        testProd.Family = 'Hardware';
        testProd.ProductCode = 'APAC2346';
        testProd.Bundle_Key__c = 'APAC2346';
        testProd.Line_of_Business__c = 'GSS';
        insert testProd;
        
        Product2 testProduct = new Product2();
         testProduct.Name = 'Mic';
       	testProduct.Region__c = 'APAC';
        testProduct.Family = 'Support';
        testProduct.ProductCode = 'APAC2346';
        testProduct.Bundle_Key__c = 'APAC2346';
        testProduct.Line_of_Business__c = 'GSS';
        insert testProduct;
        
        Product2 prod = new Product2();
        prod.Name = 'testProd';
       	prod.Region__c = 'APAC';
        prod.Family = 'Practice Performance';
        prod.ProductCode = 'APAC2346';
        prod.Bundle_Key__c = 'APAC2346';
        prod.Line_of_Business__c = 'GSS';
        insert prod;
     
        List<Asset> asstList = new List<Asset>();
  string supportRecId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Support').getRecordTypeId();

         Asset asst = new Asset();
        asst.RecordTypeId =supportRecId;
        asst.Name = 'Test Asset';
        asst.AccountID =acc.ID;
        asst.Status = 'Purchased';
        asst.Product2Id = testProduct.Id;
        
        insert asst;
        asstList.add(asst);
          string recordtypeId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Practice Performance').getRecordTypeId();

        Asset ast = new Asset();
        ast.RecordTypeId =recordtypeId;
        ast.Name = 'Test Asset';
        ast.AccountID =acc.ID;
        ast.SerialNumber ='testt123';
        ast.Quantity =2;
        ast.License_Expiry_Date__c=system.today();
        ast.Computer_Name__c='Test';
        ast.Version__c ='2';
        ast.Demo_Expiry_Date__c =system.today();
        ast.Update_Date__c =system.today();
        //ast.LOB__c ='Test';
        ast.Status = 'Purchased';
        ast.Product2Id = prod.Id;
        insert ast;
      
        asstList.add(asst);
         
        test.startTest();
        AssetTriggerHelper.assetCreation(asstList);
          ast.SerialNumber ='testt123';
        ast.Quantity =2;
        ast.License_Expiry_Date__c=system.today()+3;
        ast.Computer_Name__c='Test';
        ast.Version__c ='2';
        ast.Demo_Expiry_Date__c =system.today()+3;
        ast.Update_Date__c =system.today()+3;
        //ast.LOB__c ='Test';
        ast.Status = 'Purchased';
        ast.Product2Id = testProduct.Id;
        ast.Integration_Requested_Date__c =system.now();
        update ast;
        test.stopTest();
        
    }
    public static testMethod void prodFamilyCovetSoftTest(){
         Account acc =TestDataFactory.testData();

        Product2 testProd = new Product2();
        testProd.Name = 'sampleProd';
       	testProd.Region__c = 'APAC';
        testProd.Family = 'Hardware';
        testProd.ProductCode = 'APAC2346';
        testProd.Bundle_Key__c = 'APAC2346';
        testProd.Line_of_Business__c = 'GSS';
        insert testProd;
        
        Product2 testProduct = new Product2();
         testProduct.Name = 'Mic';
       	testProduct.Region__c = 'APAC';
        testProduct.Family = 'Support';
        testProduct.ProductCode = 'APAC2346';
        testProduct.Bundle_Key__c = 'APAC2346';
        testProduct.Line_of_Business__c = 'GSS';
        insert testProduct;
        
        Product2 prod = new Product2();
        prod.Name = 'testProd';
       	prod.Region__c = 'APAC';
        prod.Family = 'Covetrus Software';
        prod.ProductCode = 'APAC2346';
        prod.Bundle_Key__c = 'APAC2346';
        prod.Line_of_Business__c = 'GSS';
        insert prod;
     
        List<Asset> asstList = new List<Asset>();
  string supportRecId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Support').getRecordTypeId();

         Asset asst = new Asset();
        asst.RecordTypeId =supportRecId;
        asst.Name = 'Test Asset';
        asst.AccountID =acc.ID;
        asst.Status = 'Purchased';
        asst.Product2Id = testProduct.Id;
        
        insert asst;
        asstList.add(asst);
          string recordtypeId = Schema.SObjectType.Asset.getRecordTypeInfosByName().get('Practice Performance').getRecordTypeId();

        Asset ast = new Asset();
        ast.RecordTypeId =recordtypeId;
        ast.Name = 'Test Asset';
        ast.AccountID =acc.ID;
        ast.SerialNumber ='testt123';
        ast.Quantity =2;
        ast.License_Expiry_Date__c=system.today();
        ast.Computer_Name__c='Test';
        ast.Version__c ='2';
        ast.Demo_Expiry_Date__c =system.today();
        ast.Update_Date__c =system.today();
        //ast.LOB__c ='Test';
        ast.Status = 'Purchased';
        ast.Product2Id = prod.Id;
        insert ast;
      
        asstList.add(asst);
         
        test.startTest();
        AssetTriggerHelper.assetCreation(asstList);
          ast.SerialNumber ='testt123';
        ast.Quantity =2;
        ast.License_Expiry_Date__c=system.today()+3;
        ast.Computer_Name__c='Test';
        ast.Version__c ='2';
        ast.Demo_Expiry_Date__c =system.today()+3;
        ast.Update_Date__c =system.today()+3;
        //ast.LOB__c ='Test';
        ast.Status = 'Purchased';
        ast.Product2Id = testProduct.Id;
        ast.Integration_Requested_Date__c =system.now();
        update ast;
        test.stopTest();
        
    }
}