force-app/main/default/objects/Archive_Error_Logger__c/Archive_Error_Logger__c.object-meta.xml
<CustomObject>
    <label>Archive Error Logger</label>
    <nameField>
        <label>Archive EL Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Archive Error Logger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Archive_Error_Logger__c/fields/Brief_Description__c.field-meta.xml
<CustomField>
    <fullName>Brief_Description__c</fullName>
    <label>Brief Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Archive_Error_Logger__c/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <label>Component Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Apex Class</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Approval Process</fullName>
            </value>
            <value>
                <fullName>Workflow</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Visualforce Page</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Archive_Error_Logger__c/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <label>Input</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Archive_Error_Logger__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Archive_Error_Logger__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Archive_Error_Logger__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Archive_Error_Logger__c/fields/Transaction_Date__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Date__c</fullName>
    <label>Transaction Date</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Archive_Error_Logger__c/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <label>User ID</label>
    <length>34</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Archive_Error_Logger__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Archive Error Logger</relationshipLabel>
    <relationshipName>Archive_Error_Logger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/Error_Logger__c.object-meta.xml
<CustomObject>
    <label>Error Logger</label>
    <nameField>
        <displayFormat>IN-{0}</displayFormat>
        <label>Incident Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Loggers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Logger__c/fields/Brief_Description__c.field-meta.xml
<CustomField>
    <fullName>Brief_Description__c</fullName>
    <description>This is to store the short descripton of the error message</description>
    <label>Brief Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <description>This is to store the name of the process that is being executed</description>
    <label>Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <description>This is to store the name type of the process that is being executed</description>
    <label>Component Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Workflow</fullName>
            </value>
            <value>
                <fullName>Apex Class</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Apex Job</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>This is to store the complete details of the error.</description>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Input__c.field-meta.xml
<CustomField>
    <fullName>Input__c</fullName>
    <description>This is to store the Input(Parameter) that is provided for the particular method.</description>
    <inlineHelpText>This contains the data that is used while issue is raised.</inlineHelpText>
    <label>Input</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>This is to store the Name of the Object that Process,Trigger has.</description>
    <label>Object Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <description>This is to store the Identify the severity of the record.</description>
    <label>Severity</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/TransactionDateTime__c.field-meta.xml
<CustomField>
    <fullName>TransactionDateTime__c</fullName>
    <description>This is to store the transaction time</description>
    <label>TransactionDateTime</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/User_ID__c.field-meta.xml
<CustomField>
    <fullName>User_ID__c</fullName>
    <label>User ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Error_Logger__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Error_Loggers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ErrorloggerSchedulerHelper.cls
/**************************************************************************************************
*** Trigger Name           : ErrorloggerSchedulerHelper
*** Class Description      : This Class fetches all the records whose archieval date is current date move into Archive from error.
                             This class is invoked by a scheduler class ErrorloggerScheduleClass logger
*** Author                 : Coreflex Solutions
*** Class Created Date     : 
*** Configurable Parameters:
*        End Point URL     :
*        Custom Labels Used:
*        Custom Object Used: 
*** Change Management      :
*        Change #          : 
*        Change Description:
*        Modified Date     :
*        Modified By       :
**************************************************************************************************/
public class ErrorloggerSchedulerHelper {
    
/**************************************************************************************************
*** Method Name             : moveRecordsToArchieve
*** Method Description      : This method removes the record from error logger and archieves it.
**********************************************************************************************************/
public static void moveRecordsToArchieve( List<Error_Logger__c> errorLoggerRecordsList){
        list<Archive_Error_Logger__c> archiveList = new list<Archive_Error_Logger__c>();
            for(Error_Logger__c errLogRecord : errorLoggerRecordsList){
                Archive_Error_Logger__c archieveRec = new Archive_Error_Logger__c();
                archieveRec.name = errLogRecord.Name;
                archieveRec.Brief_Description__c = errLogRecord.Brief_Description__c;
                archieveRec.Close_Date__c = errLogRecord.Closed_Date__c;
                archieveRec.Component_Name__c = errLogRecord.Component_Name__c;
                archieveRec.Component_Type__c = errLogRecord.Component_Type__c;
                archieveRec.Error_Message__c = errLogRecord.Error_Message__c;
                archieveRec.Input__c = errLogRecord.Input__c;
                archieveRec.Object_Name__c = errLogRecord.Object_Name__c;
                archieveRec.Severity__c = errLogRecord.Severity__c;
                archieveRec.Status__c = errLogRecord.Status__c;
                archieveRec.Transaction_Date__c = errLogRecord.TransactionDateTime__c;
                archieveRec.User_ID__c = errLogRecord.User_ID__c;
                archieveRec.User_Name__c = errLogRecord.User_Name__c;
                archiveList.add(archieveRec);
            }	
            if(archiveList.size()>0){
            insert archiveList;
            delete errorLoggerRecordsList;
            }
        
        
    }
   
}