force-app/main/default/objects/Lead/fields/Lead_Interest__c.field-meta.xml
<CustomField>
    <fullName>Lead_Interest__c</fullName>
    <description>Unrestricted picklist values for this picklist field</description>
    <label>Lead Interest</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACESoft Business Manager</fullName>
            </value>
            <value>
                <fullName>Advantage+ Software</fullName>
            </value>
            <value>
                <fullName>AHMS</fullName>
            </value>
            <value>
                <fullName>AIS</fullName>
            </value>
            <value>
                <fullName>AlisVet</fullName>
            </value>
            <value>
                <fullName>AltaPoint Veterinary Software</fullName>
            </value>
            <value>
                <fullName>Animal Intelligence</fullName>
            </value>
            <value>
                <fullName>Animana</fullName>
            </value>
            <value>
                <fullName>Ardex</fullName>
            </value>
            <value>
                <fullName>Aria</fullName>
            </value>
            <value>
                <fullName>ATSystems</fullName>
            </value>
            <value>
                <fullName>AutoTrack</fullName>
            </value>
            <value>
                <fullName>AVImark Software</fullName>
            </value>
            <value>
                <fullName>Bastet Windows</fullName>
            </value>
            <value>
                <fullName>BeeFree</fullName>
            </value>
            <value>
                <fullName>Ciderhouse</fullName>
            </value>
            <value>
                <fullName>ClienTrax</fullName>
            </value>
            <value>
                <fullName>Client Recapture</fullName>
            </value>
            <value>
                <fullName>ClinicWare</fullName>
            </value>
            <value>
                <fullName>Complete Clinic Software</fullName>
            </value>
            <value>
                <fullName>Cornerstone</fullName>
            </value>
            <value>
                <fullName>Credit Card Processing</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Customer Logic</fullName>
            </value>
            <value>
                <fullName>Data Backup</fullName>
            </value>
            <value>
                <fullName>Dunlops - Vetsys</fullName>
            </value>
            <value>
                <fullName>DVMAX Practice</fullName>
            </value>
            <value>
                <fullName>EasyVet</fullName>
            </value>
            <value>
                <fullName>EazyVetPro</fullName>
            </value>
            <value>
                <fullName>ePetHealth</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Source_Description__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source_Description__c</fullName>
    <description>CCRM-2292</description>
    <label>Lead Source Description</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Lead_Sub_Source__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>Capterra</fullName>
            </value>
            <value>
                <fullName>G2</fullName>
            </value>
            <value>
                <fullName>Google Ads</fullName>
            </value>
            <value>
                <fullName>Paid Facebook</fullName>
            </value>
            <value>
                <fullName>Paid LinkedIn</fullName>
            </value>
            <value>
                <fullName>Paid Twitter</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Site Visit</fullName>
            </value>
            <value>
                <fullName>HubSpot</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_Source__c</fullName>
    <description>CCRM-2292</description>
    <label>Lead Sub-Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>Event</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Inbound</fullName>
            </value>
            <value>
                <fullName>Outbound</fullName>
            </value>
            <value>
                <fullName>Quarterly Call</fullName>
            </value>
            <value>
                <fullName>Workshop</fullName>
            </value>
            <value>
                <fullName>Training Call</fullName>
            </value>
            <value>
                <fullName>Site Visit</fullName>
            </value>
            <value>
                <fullName>CO APAC</fullName>
            </value>
            <value>
                <fullName>CO UK</fullName>
            </value>
            <value>
                <fullName>CO NA</fullName>
            </value>
            <value>
                <fullName>CCG AU</fullName>
            </value>
            <value>
                <fullName>VetQuip AU</fullName>
            </value>
            <value>
                <fullName>VI AU</fullName>
            </value>
            <value>
                <fullName>GSS APAC</fullName>
            </value>
            <value>
                <fullName>GSS EMEA</fullName>
            </value>
            <value>
                <fullName>GSS NA</fullName>
            </value>
            <value>
                <fullName>Direct Mail</fullName>
            </value>
            <value>
                <fullName>Internal Referral</fullName>
            </value>
            <value>
                <fullName>Field Rep Referral</fullName>
            </value>
            <value>
                <fullName>Cold Call</fullName>
            </value>
            <value>
                <fullName>Key Account Manager</fullName>
            </value>
            <value>
                <fullName>Corporate Account Manager</fullName>
            </value>
            <value>
                <fullName>Practice Support (PST)</fullName>
            </value>
            <value>
                <fullName>Pharmacy Transfer (PTP)</fullName>
            </value>
            <value>
                <fullName>Tradeshow</fullName>
            </value>
            <value>
                <fullName>Email Campaign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Line of Business</label>
    <referenceTo>Line_of_Business__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/recordTypes/NA.recordType-meta.xml
<RecordType>
    <fullName>NA</fullName>
    <active>true</active>
    <businessProcess>Lead Process</businessProcess>
    <label>NA</label>
</RecordType>

force-app/main/default/objects/Line_of_Business__c/Line_of_Business__c.object-meta.xml
<CustomObject>
    <label>Line of Business</label>
    <nameField>
        <label>Line of Business Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line of Businesses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Line_of_Business__c/fields/Line_of_Business__c.field-meta.xml
<CustomField>
    <fullName>Line_of_Business__c</fullName>
    <label>Line of Business</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GSS</fullName>
            </value>
            <value>
                <fullName>GPM</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>Specialty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadHelper.cls
// LeadHelper
// Bhanudas Tanaka - Covetrus - Feb 2020
// --------------------------------------
// Provides CRUD sObject interface for interacting with Leads

public without sharing class LeadHelper {
    
    static public void createLeadFromForm ( LeadFormController.LeadForm leadData ) {

        try {
            // get the record type and other values
            RecordType naRt = [ SELECT Id, Name FROM RecordType WHERE Name = 'NA' and sObjectType = 'Lead' ];
            //Line_Of_Business__c lob = [ SELECT Id, Name FROM Line_Of_Business__c WHERE Name = 'GSS NA' ];
            
            // create the lead
            Lead newLead = new Lead ();
            newLead.recordTypeId = naRt.Id;
            newLead.Status = 'New';
            newLead.FirstName = leadData.pcFirstName;
            newLead.LastName = leadData.pcLastName;
            newLead.Email = leadData.pcEmail;
            newLead.Phone = leadData.pcPhone;
            newLead.Company = leadData.accountName;
            //newLead.Line_Of_Business__c = lob.Id;
            newLead.CurrencyIsoCode = 'USD';
            newLead.LeadSource = 'Internal Referral';
            newLead.Lead_Sub_Source__c = 'CO NA';
            //newLead.Lead_Source_Description__c = '???'
            //newLead.Lead_Interest__c = need to map
            newLead.State = leadData.stateProvince;
            newLead.Country = 'United States';
            //newLead.Referral_Source_Name__c = leadData.famFirstName + ' ' + leadData.famLastName;
            //newLead.Referral_Source_Email__c = leadData.famEmail;
            insert newLead;
        } catch ( Exception e ) {
            throw new LeadFormException ( 'An Error Occurred in Creating Lead', e.getMessage(), true );
        }
        
    }
}