force-app/main/default/objects/CCV_Processor__mdt/CCV_Processor__mdt.object-meta.xml
<CustomObject>
    <description>Defines and indicates active Covetrus Customer View processor</description>
    <label>CCV Processor</label>
    <pluralLabel>CCV Processors</pluralLabel>
</CustomObject>

force-app/main/default/objects/CCV_Processor__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Sets processor as active (note: only one should be active at any given time)</description>
    <inlineHelpText>Sets processor as active (note: only one should be active at any given time).</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CCV_Processor__mdt/fields/Processor_Class__c.field-meta.xml
<CustomField>
    <fullName>Processor_Class__c</fullName>
    <description>API Name of the Processor Class used to query data for CCV</description>
    <inlineHelpText>API Name of the Processor Class used to query data for CCV</inlineHelpText>
    <label>Processor Class</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Covetrus_Environment__c/Covetrus_Environment__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>A collection of settings for our Covetrus operating environment</description>
    <label>Covetrus Environment</label>
</CustomObject>

force-app/main/default/objects/Covetrus_Environment__c/fields/Covetrus_Shared_View_Service_Name__c.field-meta.xml
<CustomField>
    <fullName>Covetrus_Shared_View_Service_Name__c</fullName>
    <description>Name related to custom metadata for Boomi connectivity for Covetrus Shared View</description>
    <inlineHelpText>Name related to custom metadata for Boomi connectivity for Covetrus Shared View</inlineHelpText>
    <label>Covetrus Shared View Service Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Covetrus_Environment__c/fields/Shared_View_Request_Timeout__c.field-meta.xml
<CustomField>
    <fullName>Shared_View_Request_Timeout__c</fullName>
    <description>Integer value in millisecond for CCV Request Timeout value (min 2000)</description>
    <inlineHelpText>Integer value in millisecond for CCV Request Timeout value (min 2000)</inlineHelpText>
    <label>Shared View Request Timeout</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ccv_Environment.cls
public class ccv_Environment {

        public string ccvEndpointName;
        public integer requestTimeout;
        public string ccvProcessorClass;

        private Covetrus_Environment__c env;
        private CCV_Processor__mdt processor;

        // constructor - loads organizational defaults
        public ccv_Environment ( ) {
            // Fetch Custom Settings for Covetrus Values
            this.env = Covetrus_Environment__c.getOrgDefaults ();
            // Fetch Custom Metadata or initialize
            List < CCV_Processor__mdt > processors = new List < CCV_Processor__mdt > ([ SELECT Processor_Class__c FROM CCV_Processor__mdt WHERE Is_Active__c = TRUE ]);
            if ( processors.size () > 0 ) {
                this.processor = processors[0];
            } else {
                this.processor = new CCV_Processor__mdt ();
            }
        }

        // reads from custom setting
        public boolean load () {

            // read values
            this.ccvEndpointName = this.env.Covetrus_Shared_View_Service_Name__c;
            try {
                this.requestTimeout = Integer.valueOf ( this.env.Shared_View_Request_Timeout__c );
            } catch ( Exception e ) {
                // ignore, we'll just default
                this.requestTimeout = 0;
            }

            // processor class
            this.ccvProcessorClass = this.processor.Processor_Class__c;

            // handle timeout defaults
            if (( this.requestTimeout == null ) || ( this.requestTimeout < 2000 )) {
                // default to 2000 - 2 secs
                this.requestTimeout = 2000;
            }
            // if endpoint available, return true, else false
            if (( this.ccvEndpointName == null ) || ( this.ccvEndpointName == '' )) {
                return false;
            } else {
                return true;
            }
        }
    }